#!/usr/bin/env python3
"""
Script to convert CSV food dictionary to JSON format
"""

import csv
import json
import uuid
import pandas as pd
from datetime import datetime

def convert_csv_to_csv(csv_file_path, output_csv_path):
    """
    Convert CSV food dictionary to new CSV format with the specified structure
    """
    
    # Define the field names for the new CSV structure
    fieldnames = [
        "english_name", "source", "portion_name", "Water", "Galactose", "Lactose", "Lycopene",
        "Energy", "Protein", "Ash", "Sucrose", "Maltose", "Riboflavin", "Cholesterol", "Starch",
        "Nitrogen", "Fructose", "Niacin", "Cryptoxanthin__beta", "Tocopherol__delta", "Tocotrienol__gamma",
        "Tocotrienol__delta", "Vitamin_C__total_ascorbic_acid", "Thiamin", "Folate__total",
        "Vitamin_K__Dihydrophylloquinone_", "Vitamin_K__phylloquinone_", "Fatty_acids__total_trans",
        "Fatty_acids__total_saturated", "SFA_8_0", "SFA_12_0", "SFA_14_0", "PUFA_22_6_n_3__DHA_",
        "SFA_22_0", "PUFA_20_5_n_3__EPA_", "PUFA_22_5_n_3__DPA_", "SFA_17_0", "SFA_24_0", "TFA_16_1_t",
        "MUFA_24_1_c", "MUFA_18_1_c", "PUFA_18_2_n_6_c_c", "MUFA_22_1_c", "MUFA_17_1",
        "Fatty_acids__total_trans_monoenoic", "MUFA_15_1", "PUFA_18_3_n_3_c_c_c__ALA_", "PUFA_20_3_n_3",
        "PUFA_22_4", "Fiber__total_dietary", "Iron__Fe", "Magnesium__Mg", "Phosphorus__P", "Sodium__Na",
        "Copper__Cu", "Manganese__Mn", "Vitamin_A__RAE", "Carotene__beta", "Carotene__alpha", "PUFA_20_4",
        "PUFA_18_4", "Fatty_acids__total_monounsaturated", "Fatty_acids__total_polyunsaturated", "SFA_15_0",
        "TFA_18_1_t", "TFA_22_1_t", "TFA_18_2_t_not_further_defined", "PUFA_18_2_CLAs", "PUFA_20_2_n_6_c_c",
        "MUFA_16_1_c", "PUFA_18_3_n_6_c_c_c", "Fatty_acids__total_trans_polyenoic", "PUFA_20_3_n_6",
        "SFA_4_0", "SFA_6_0", "SFA_10_0", "SFA_16_0", "SFA_18_0", "SFA_20_0", "Lutein___zeaxanthin",
        "Tocopherol__beta", "Tocopherol__gamma", "Tocotrienol__alpha", "Tocotrienol__beta", "Pantothenic_acid",
        "Vitamin_B_6", "Vitamin_K__Menaquinone_4_", "Total_lipid__fat_", "Carbohydrate__by_difference",
        "Glucose", "Calcium__Ca", "Potassium__K", "Zinc__Zn", "Selenium__Se", "MUFA_14_1_c", "MUFA_20_1_c",
        "MUFA_22_1_n_9", "PUFA_22_2", "SFA_11_0", "TFA_18_3_t", "PUFA_20_3_n_9", "Choline__total",
        "Choline__from_glycerophosphocholine", "Betaine", "Choline__from_sphingomyelin", "Choline__free",
        "Choline__from_phosphotidyl_choline", "Choline__from_phosphocholine", "Fatty_acids__total_trans_dienoic",
        "MUFA_17_1_c", "PUFA_18_2_c", "PUFA_18_3_c", "PUFA_20_3_c", "PUFA_20_4c", "PUFA_20_5c", "PUFA_22_5_c",
        "PUFA_22_6_c", "PUFA_20_2_c", "Cryptoxanthin__alpha", "trans_beta_Carotene", "cis_beta_Carotene",
        "cis_Lutein_Zeaxanthin", "cis_Lycopene", "Lutein", "Zeaxanthin", "Vitamin_B_12", "Retinol",
        "Vitamin_D2__ergocalciferol_", "Vitamin_D3__cholecalciferol_", "Vitamin_D__D2___D3_",
        "Vitamin_D__D2___D3___International_Units", "col_25_hydroxycholecalciferol", "Iodine__I", "MUFA_20_1",
        "PUFA_18_3i", "Specific_Gravity", "Tryptophan", "Threonine", "Methionine", "Phenylalanine", "Tyrosine",
        "Alanine", "Glutamic_acid", "Glycine", "Proline", "Isoleucine", "Leucine", "Lysine", "Cystine", "Valine",
        "Arginine", "Histidine", "Aspartic_acid", "Serine", "Fiber__insoluble", "Fiber__soluble", "Hydroxyproline",
        "MUFA_22_1", "MUFA_18_1", "PUFA_18_2", "PUFA_18_3", "SFA_5_0", "SFA_7_0", "SFA_9_0", "MUFA_12_1",
        "TFA_14_1_t", "TFA_20_1_t", "SFA_21_0", "MUFA_22_1_n_11", "SFA_23_0", "PUFA_22_3", "Cysteine",
        "col_10_Formyl_folic_acid__10HCOFA_", "col_5_Formyltetrahydrofolic_acid__5_HCOH4",
        "col_5_methyl_tetrahydrofolate__5_MTHF_", "Phytofluene", "Phytoene", "trans_Lycopene", "Boron__B",
        "Cobalt__Co", "Molybdenum__Mo", "Nickel__Ni", "Sulfur__S", "PUFA_20_3", "Biotin", "Beta_sitosterol",
        "Brassicasterol", "Campestanol", "Campesterol", "Delta_5_avenasterol", "Beta_sitostanol", "Stigmasterol",
        "Total_dietary_fiber__AOAC_2011_25_", "Citric_acid", "Malic_acid", "Total_Sugars",
        "Energy__Atwater_Specific_Factors_", "Delta_7_Stigmastenol", "Stigmastadiene", "TFA_18_2_t", "Ergosterol",
        "Ergothioneine", "Vitamin_D4", "Ergosta_7_enol", "Ergosta_7_22_dienol", "Ergosta_5_7_dienol", "Beta_glucan",
        "Glutathione", "Daidzin", "Genistin", "Glycitin", "Verbascose", "Raffinose", "Stachyose", "Daidzein",
        "Genistein", "Carotene__gamma", "Oxalic_acid", "Quinic_acid", "Low_Molecular_Weight_Dietary_Fiber__LMWDF_",
        "High_Molecular_Weight_Dietary_Fiber__HMWDF_", "Pyruvic_acid", "Folate__DFE", "Theobromine", "Folate__food",
        "MUFA_16_1", "Caffeine", "Vitamin_E__added", "Vitamin_B_12__added", "Alcohol__ethyl", "Folic_acid",
        "PUFA_2_4_n_6", "SFA_13_0", "PUFA_21_5", "MUFA_18_1_11_t__18_1t_n_7_", "MUFA_14_1", "Vitamin_A__IU",
        "Phytosterols", "PUFA_18_2_i", "Fluoride__F", "TFA_18_2_t_t", "PUFA_2_5_n_3__EPA_", "gtinUpc",
        "Sugars__added", "Total_sugar_alcohols", "Vitamin_E", "Sorbitol", "Taurine", "Xylitol", "Chlorine__Cl",
        "Chromium__Cr", "Inositol", "Inulin", "Sugars__intrinsic", "Acetic_acid", "Lactic_acid", "Ribose",
        "Epigallocatechin_3_gallate", "availableDate", "modifiedDate", "hebrew_name", "Vitamin_K", "brandOwner",
        "brand", "marketCountry", "ingredients", "isUpdated", "search_id"
    ]
    
    # Read CSV file using pandas to handle multiline entries better
    df = pd.read_csv(csv_file_path, encoding='utf-8')
    
    print("Columns in CSV:", df.columns.tolist())
    print("First few rows:")
    print(df.head(3))
    
    # Write new CSV
    with open(output_csv_path, 'w', encoding='utf-8', newline='') as output_csvfile:
        writer = csv.DictWriter(output_csvfile, fieldnames=fieldnames)
        writer.writeheader()
        
        for index, row in df.iterrows():
            # Create a new food item with the specified structure
            food_item = {
                "english_name": "",
                "source": "food_dictionary_merged_cleaned.csv",
                "portion_name": None,
                "Water": None,
                "Galactose": None,
                "Lactose": None,
                "Lycopene": None,
                "Energy": float(row['calories']) if pd.notna(row['calories']) else None,
                "Protein": float(row['proteins_g']) if pd.notna(row['proteins_g']) else None,
                "Ash": None,
                "Sucrose": None,
                "Maltose": None,
                "Riboflavin": None,
                "Cholesterol": float(row['cholesterol_mg']) if pd.notna(row['cholesterol_mg']) else None,
                "Starch": None,
                "Nitrogen": None,
                "Fructose": None,
                "Niacin": None,
                "Cryptoxanthin__beta": None,
                "Tocopherol__delta": None,
                "Tocotrienol__gamma": None,
                "Tocotrienol__delta": None,
                "Vitamin_C__total_ascorbic_acid": None,
                "Thiamin": None,
                "Folate__total": None,
                "Vitamin_K__Dihydrophylloquinone_": None,
                "Vitamin_K__phylloquinone_": None,
                "Fatty_acids__total_trans": float(row['trans_fat_g']) if pd.notna(row['trans_fat_g']) else None,
                "Fatty_acids__total_saturated": float(row['saturated_fat_g']) if pd.notna(row['saturated_fat_g']) else None,
                "SFA_8_0": None,
                "SFA_12_0": None,
                "SFA_14_0": None,
                "PUFA_22_6_n_3__DHA_": None,
                "SFA_22_0": None,
                "PUFA_20_5_n_3__EPA_": None,
                "PUFA_22_5_n_3__DPA_": None,
                "SFA_17_0": None,
                "SFA_24_0": None,
                "TFA_16_1_t": None,
                "MUFA_24_1_c": None,
                "MUFA_18_1_c": None,
                "PUFA_18_2_n_6_c_c": None,
                "MUFA_22_1_c": None,
                "MUFA_17_1": None,
                "Fatty_acids__total_trans_monoenoic": None,
                "MUFA_15_1": None,
                "PUFA_18_3_n_3_c_c_c__ALA_": None,
                "PUFA_20_3_n_3": None,
                "PUFA_22_4": None,
                "Fiber__total_dietary": None,
                "Iron__Fe": None,
                "Magnesium__Mg": None,
                "Phosphorus__P": None,
                "Sodium__Na": float(row['sodium_mg']) if pd.notna(row['sodium_mg']) else None,
                "Copper__Cu": None,
                "Manganese__Mn": None,
                "Vitamin_A__RAE": None,
                "Carotene__beta": None,
                "Carotene__alpha": None,
                "PUFA_20_4": None,
                "PUFA_18_4": None,
                "Fatty_acids__total_monounsaturated": None,
                "Fatty_acids__total_polyunsaturated": None,
                "SFA_15_0": None,
                "TFA_18_1_t": None,
                "TFA_22_1_t": None,
                "TFA_18_2_t_not_further_defined": None,
                "PUFA_18_2_CLAs": None,
                "PUFA_20_2_n_6_c_c": None,
                "MUFA_16_1_c": None,
                "PUFA_18_3_n_6_c_c_c": None,
                "Fatty_acids__total_trans_polyenoic": None,
                "PUFA_20_3_n_6": None,
                "SFA_4_0": None,
                "SFA_6_0": None,
                "SFA_10_0": None,
                "SFA_16_0": None,
                "SFA_18_0": None,
                "SFA_20_0": None,
                "Lutein___zeaxanthin": None,
                "Tocopherol__beta": None,
                "Tocopherol__gamma": None,
                "Tocotrienol__alpha": None,
                "Tocotrienol__beta": None,
                "Pantothenic_acid": None,
                "Vitamin_B_6": None,
                "Vitamin_K__Menaquinone_4_": None,
                "Total_lipid__fat_": float(row['fats_g']) if pd.notna(row['fats_g']) else None,
                "Carbohydrate__by_difference": float(row['carbohydrates_g']) if pd.notna(row['carbohydrates_g']) else None,
                "Glucose": None,
                "Calcium__Ca": float(row['calcium_mg']) if pd.notna(row['calcium_mg']) else None,
                "Potassium__K": None,
                "Zinc__Zn": None,
                "Selenium__Se": None,
                "MUFA_14_1_c": None,
                "MUFA_20_1_c": None,
                "MUFA_22_1_n_9": None,
                "PUFA_22_2": None,
                "SFA_11_0": None,
                "TFA_18_3_t": None,
                "PUFA_20_3_n_9": None,
                "Choline__total": None,
                "Choline__from_glycerophosphocholine": None,
                "Betaine": None,
                "Choline__from_sphingomyelin": None,
                "Choline__free": None,
                "Choline__from_phosphotidyl_choline": None,
                "Choline__from_phosphocholine": None,
                "Fatty_acids__total_trans_dienoic": None,
                "MUFA_17_1_c": None,
                "PUFA_18_2_c": None,
                "PUFA_18_3_c": None,
                "PUFA_20_3_c": None,
                "PUFA_20_4c": None,
                "PUFA_20_5c": None,
                "PUFA_22_5_c": None,
                "PUFA_22_6_c": None,
                "PUFA_20_2_c": None,
                "Cryptoxanthin__alpha": None,
                "trans_beta_Carotene": None,
                "cis_beta_Carotene": None,
                "cis_Lutein_Zeaxanthin": None,
                "cis_Lycopene": None,
                "Lutein": None,
                "Zeaxanthin": None,
                "Vitamin_B_12": None,
                "Retinol": None,
                "Vitamin_D2__ergocalciferol_": None,
                "Vitamin_D3__cholecalciferol_": None,
                "Vitamin_D__D2___D3_": None,
                "Vitamin_D__D2___D3___International_Units": None,
                "col_25_hydroxycholecalciferol": None,
                "Iodine__I": None,
                "MUFA_20_1": None,
                "PUFA_18_3i": None,
                "Specific_Gravity": None,
                "Tryptophan": None,
                "Threonine": None,
                "Methionine": None,
                "Phenylalanine": None,
                "Tyrosine": None,
                "Alanine": None,
                "Glutamic_acid": None,
                "Glycine": None,
                "Proline": None,
                "Isoleucine": None,
                "Leucine": None,
                "Lysine": None,
                "Cystine": None,
                "Valine": None,
                "Arginine": None,
                "Histidine": None,
                "Aspartic_acid": None,
                "Serine": None,
                "Fiber__insoluble": None,
                "Fiber__soluble": None,
                "Hydroxyproline": None,
                "MUFA_22_1": None,
                "MUFA_18_1": None,
                "PUFA_18_2": None,
                "PUFA_18_3": None,
                "SFA_5_0": None,
                "SFA_7_0": None,
                "SFA_9_0": None,
                "MUFA_12_1": None,
                "TFA_14_1_t": None,
                "TFA_20_1_t": None,
                "SFA_21_0": None,
                "MUFA_22_1_n_11": None,
                "SFA_23_0": None,
                "PUFA_22_3": None,
                "Cysteine": None,
                "col_10_Formyl_folic_acid__10HCOFA_": None,
                "col_5_Formyltetrahydrofolic_acid__5_HCOH4": None,
                "col_5_methyl_tetrahydrofolate__5_MTHF_": None,
                "Phytofluene": None,
                "Phytoene": None,
                "trans_Lycopene": None,
                "Boron__B": None,
                "Cobalt__Co": None,
                "Molybdenum__Mo": None,
                "Nickel__Ni": None,
                "Sulfur__S": None,
                "PUFA_20_3": None,
                "Biotin": None,
                "Beta_sitosterol": None,
                "Brassicasterol": None,
                "Campestanol": None,
                "Campesterol": None,
                "Delta_5_avenasterol": None,
                "Beta_sitostanol": None,
                "Stigmasterol": None,
                "Total_dietary_fiber__AOAC_2011_25_": None,
                "Citric_acid": None,
                "Malic_acid": None,
                "Total_Sugars": float(row['sugars_g']) if pd.notna(row['sugars_g']) else None,
                "Energy__Atwater_Specific_Factors_": None,
                "Delta_7_Stigmastenol": None,
                "Stigmastadiene": None,
                "TFA_18_2_t": None,
                "Ergosterol": None,
                "Ergothioneine": None,
                "Vitamin_D4": None,
                "Ergosta_7_enol": None,
                "Ergosta_7_22_dienol": None,
                "Ergosta_5_7_dienol": None,
                "Beta_glucan": None,
                "Glutathione": None,
                "Daidzin": None,
                "Genistin": None,
                "Glycitin": None,
                "Verbascose": None,
                "Raffinose": None,
                "Stachyose": None,
                "Daidzein": None,
                "Genistein": None,
                "Carotene__gamma": None,
                "Oxalic_acid": None,
                "Quinic_acid": None,
                "Low_Molecular_Weight_Dietary_Fiber__LMWDF_": None,
                "High_Molecular_Weight_Dietary_Fiber__HMWDF_": None,
                "Pyruvic_acid": None,
                "Folate__DFE": None,
                "Theobromine": None,
                "Folate__food": None,
                "MUFA_16_1": None,
                "Caffeine": None,
                "Vitamin_E__added": None,
                "Vitamin_B_12__added": None,
                "Alcohol__ethyl": None,
                "Folic_acid": None,
                "PUFA_2_4_n_6": None,
                "SFA_13_0": None,
                "PUFA_21_5": None,
                "MUFA_18_1_11_t__18_1t_n_7_": None,
                "MUFA_14_1": None,
                "Vitamin_A__IU": None,
                "Phytosterols": None,
                "PUFA_18_2_i": None,
                "Fluoride__F": None,
                "TFA_18_2_t_t": None,
                "PUFA_2_5_n_3__EPA_": None,
                "gtinUpc": None,
                "Sugars__added": None,
                "Total_sugar_alcohols": None,
                "Vitamin_E": None,
                "Sorbitol": None,
                "Taurine": None,
                "Xylitol": None,
                "Chlorine__Cl": None,
                "Chromium__Cr": None,
                "Inositol": None,
                "Inulin": None,
                "Sugars__intrinsic": None,
                "Acetic_acid": None,
                "Lactic_acid": None,
                "Ribose": None,
                "Epigallocatechin_3_gallate": None,
                "availableDate": datetime.now().isoformat() + "Z",
                "modifiedDate": datetime.now().isoformat() + "Z",
                "hebrew_name": str(row['product_name']) if pd.notna(row['product_name']) else '',
                "Vitamin_K": None,
                "brandOwner": str(row['brand_name']) if pd.notna(row['brand_name']) else '',
                "brand": None,
                "marketCountry": "Israel",
                "ingredients": str(row['ingredients']) if pd.notna(row['ingredients']) else '',
                "isUpdated": None,
                "search_id": str(uuid.uuid4().int)[:7]
            }
            
            writer.writerow(food_item)
    
    print(f"Successfully converted food items from CSV to new CSV format")
    print(f"Output saved to: {output_csv_path}")

if __name__ == "__main__":
    # Convert the CSV file
    convert_csv_to_csv('food_dictionary_merged_cleaned.csv', 'food_dictionary_new_format.csv')
