import React, { createContext, useState, useContext } from 'react';
import { EventBus } from '@/utils/EventBus';

export const LanguageContext = createContext();

export const languages = {
  en: 'en',
  he: 'he'
};

export const translations = {
  en: {
    // Navigation & Main Pages
    home: 'Dashboard',
    dashboard: 'Dashboard',
    about: 'About',
    services: 'Services',
    contact: 'Contact',
    chat: 'Chat',
    allChats: 'All Chats',
    dataGenerator: 'Data Generator',
    nutritionPlan: 'Nutrition Plan',
    menuCreate: 'Create Meal Plan',
    menuEdit: 'Edit Meal Plan',
    menuView: 'View Meal Plan',
    menuLoad: 'Load Meal Plan',
    menuAnalysis: 'Meal Plan Analysis',
    menus: 'Meal Plans',
    apiMenus: 'API Meal Plans',
    clients: 'Clients',
    clientProfile: 'Client Profile',
    clientMenu: 'Client Meal Plan',
    apiClientMenu: 'API Client Meal Plan',
    editClient: 'Edit Client',
    users: 'Users',
    recipes: 'Recipes',
    recipesPage: 'Recipes',
    weightLogs: 'Weight Logs',
    menuload: 'Load Meal Plan',
    settings: 'Settings',
    register: 'Register',
    login: 'Login',
    
    // Common buttons and labels
    submit: 'Submit',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    signOut: 'Sign Out',
    retry: 'Retry',
    edit: 'Edit',
    loading: 'Loading...',
    search: 'Search',
    close: 'Close',
    open: 'Open',
    next: 'Next',
    previous: 'Previous',
    send: 'Send',
    upload: 'Upload',
    download: 'Download',
    settings: 'Settings',
    profile: 'Profile',
    back: 'Back',
    continue: 'Continue',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    
    // Client selection
    selectClient: 'Select a client',
    
    // Language switch
    switchLanguage: 'עברית',
    
    // Error messages
    connectionError: 'Connection Error',
    failedToLoad: 'Failed to load user data. Please try refreshing the page.',
    
    // Chat page
    selectClientToChat: 'Select Client to Chat With',
    chooseClientFromList: 'Choose a client from your list to start chatting',
    selectAClient: 'Select a client...',
    chatWith: 'Chat with',
    clientCode: 'Client Code',
    dailyCalories: 'Daily calories',
    notSet: 'Not set',
    startConversation: 'Start a Conversation',
    chatAboutNutrition: 'about their nutrition plan. You can also share food images for analysis.',
    noClientSelected: 'No Client Selected',
    selectClientToStart: 'Please select a client from the dropdown above to start chatting about their nutrition plan.',
    messageClient: 'Message',
    imageSelected: 'Image selected',
    uploadedFood: 'Uploaded food',
    failedToUpload: 'Failed to upload image. Please try again.',
    failedToSend: 'Failed to send message. Please try again.',
    failedToLoadClients: 'Failed to load clients. Please try again later.',
    failedToLoadClientData: 'Failed to load client data. Please try again later.',
    
    // Login page
    login: 'Login',
    enterCredentials: 'Enter your credentials to access your account',
    email: 'Email',
    enterEmail: 'Enter your email',
    password: 'Password',
    enterPassword: 'Enter your password',
    signIn: 'Sign In',
    signingIn: 'Signing in...',
    dontHaveAccount: "Don't have an account?",
    register: 'Register',
    failedToSignIn: 'Failed to sign in. Please check your credentials and try again.',
    
    // Users page
    userManagement: 'User Management',
    manageUserProfiles: 'Manage user profiles and dietary information',
    searchUsers: 'Search users...',
    users: 'Users',
    viewAndManageUsers: 'View and manage all registered users',
    userCode: 'User Code',
    details: 'Details',
    actions: 'Actions',
    noData: 'No data',
    noUsersFound: 'No users found',
    editUserInformation: 'Edit User Information',
    editUserDescription: 'Update the client\'s information and preferences.',
    addUserDescription: 'Add a new client to your practice.',
    heightCm: 'Height (cm)',
    weightKg: 'Weight (kg)',
    gender: 'Gender',
    activity: 'Activity',
    goal: 'Goal',
    selectGender: 'Select gender',
    male: 'Male',
    female: 'Female',
    selectActivityLevel: 'Select activity level',
    sedentary: 'Sedentary (little to no exercise)',
    lightActivity: 'Light Activity (light exercise/sports 1-3 days/week)',
    moderateActivity: 'Moderate Activity (moderate exercise/sports 3-5 days/week)',
    veryActive: 'Very Active (hard exercise/sports 6-7 days a week)',
    extraActive: 'Extra Active (very hard exercise/sports & a physical job)',
    selectGoal: 'Select goal',
    loseWeight: 'Lose Weight',
    maintainWeight: 'Maintain Weight',
    gainWeight: 'Gain Weight',
    saveChanges: 'Save Changes',
    clientManagement: 'Client Management',
    manageClientProfiles: 'Manage your client profiles and information',
    addNewClient: 'Add New Client',
    searchClients: 'Search clients by name, email, code, or phone...',
    clients: 'Clients',
    viewAndManageClients: 'View and manage your client profiles',
    showAll: 'Show All',
    showLess: 'Show Less',
    of: 'of',
    noClientsFound: 'No clients found matching your search',
    noClientsFoundGeneral: 'No clients found. Add your first client to get started.',
    contact: 'Contact',
    physical: 'Physical',
    goals: 'Goals',
    macros: 'Macros',
    name: 'Name',
    yearsOld: 'years old',
    city: 'City',
    noDataAvailable: 'No data',
    invalidBmiData: 'Invalid BMI data',
    activityLevel: 'Activity Level',
    activity: 'activity',
    kcalPerDay: 'kcal/day',
    noMacrosSet: 'No macros set',
    basicInformation: 'Basic Information',
    clientCode: 'Client Code',
    fullName: 'Full Name',
    email: 'Email',
    phoneNumber: 'Phone Number',
    dateOfBirth: 'Date of Birth',
    physicalInformation: 'Physical Information',
    age: 'Age',
    weight: 'Weight',
    height: 'Height',
    other: 'Other',
    toning: 'Toning',
    buildMuscle: 'Build Muscle',
    improveHealth: 'Improve Health',
    nutritionInformation: 'Nutrition Information',
    dailyTotalCalories: 'Daily Total Calories',
    autoCalculated: 'Auto-calculated',
    harrisBenedictInfo: 'Based on Harris-Benedict equation using age, gender, weight, height, activity level, and goal',
    mifflinStJeorInfo: 'Based on Mifflin-St Jeor equation using age, gender, weight, height, activity level, and goal',
    fillRequiredFieldsToCalculate: 'Fill required fields to calculate',
    isRequired: 'is required',
    ageCalculatedFromBirthDate: 'Age calculated from birth date',
    enterAgeOrBirthDate: 'Enter age or birth date',
    numberOfMeals: 'Number of Meals',
    region: 'Region',
    macrosGrams: 'Macros (grams)',
    protein: 'Protein',
    ingredients: 'Ingredients',
    carbs: 'Carbohydrates',
    fat: 'Fat',
    grams: 'grams',
    totalPercentages: 'Total Percentages',
    totalCaloriesInTargets: 'Total Calories in Targets',
    macrosSumMatches: 'The sum of macros always matches calories:',
    caloriesFormula: 'calories = (4 × protein) + (4 × carbs) + (9 × fat)',
    dietaryInformation: 'Dietary Information',
    foodAllergies: 'Food Allergies',
    foodAllergiesPlaceholder: 'e.g., nuts, dairy, shellfish (separate with commas)',
    foodLimitations: 'Food Limitations',
    foodLimitationsPlaceholder: 'Simple text: vegetarian, kosher, low sodium',
    foodLimitationsHelp: '✨ Enter simple text like "vegetarian, kosher" and it will auto-convert to ["vegetarian", "kosher"]',
    clientPreferences: 'Client Preferences',
    foodDiary: 'Food Diary',
    clientPreferencesPlaceholder: 'Simple text: loves pasta, mediterranean cuisine, quick meals',
    clientPreferencesHelp: '✨ Enter simple text like "loves pasta" and it will auto-convert to ["loves pasta"]',
    recommendations: 'Recommendations',
    recommendationsPlaceholder: 'Simple text: drink more water, take vitamin D, exercise 30min daily',
    recommendationsHelp: '✨ Enter simple text and it will auto-convert to structured recommendations',
    saving: 'Saving...',
    updateClient: 'Update Client',
    addClient: 'Add Client',
    failedToLoadClients: 'Failed to load clients. Please try again.',
    failedToSaveClient: 'Failed to save client:',
    failedToUpdateClient: 'Failed to update client:',
    failedToCreateClient: 'Failed to create client:',
    failedToDeleteClient: 'Failed to delete client',
    confirmDelete: 'Are you sure you want to delete',
    clientDeleted: 'Client deleted successfully',
    deleteWarning: 'This action cannot be undone.',
    foodLogsFound: 'Food logs found',
    entriesFound: 'entries found',
    preferencesAutoPopulated: 'Preferences auto-populated',
    autoPopulated: 'Auto-populated',
    translateToHebrew: 'Translate to Hebrew',
    viewDetailedAnalysis: 'View Detailed Nutritional Analysis',
    detailedAnalysis: 'Detailed Nutritional Analysis',
    comprehensiveAnalysis: 'Comprehensive analysis of client\'s eating habits with improvement recommendations',
    analysisSummary: 'Analysis Summary',
    totalEntries: 'Total Entries',
    uniqueFoods: 'Unique Foods',
    mealCategories: 'Meal Categories',
    analysisDate: 'Analysis Date',
    topFoodsByMeal: 'Top Foods by Meal Category',
    times: 'times',
    aiDietitianPrompt: 'AI Dietitian Analysis Prompt',
    nutritionalAnalysis: 'Nutritional Analysis',
    analysisDescription: 'AI-generated analysis of the client\'s eating habits with personalized improvement recommendations.',
    copySystemPrompt: 'Copy System Prompt',
    copyAnalysis: 'Copy Analysis',
    systemPromptCopied: 'System prompt copied to clipboard!',
    analysisCopied: 'Analysis copied to clipboard!',
    
    // BMI Status
    underweight: 'Underweight',
    normal: 'Normal',
    overweight: 'Overweight',
    obese: 'Obese',
    
    // Goal values
    lose: 'Lose Weight',
    maintain: 'Maintain Weight',
    gain: 'Gain Weight',
    muscle: 'Build Muscle',
    health: 'Improve Health',
    
    // Activity values
    sedentary: 'Sedentary (little to no exercise)',
    light: 'Light Activity (light exercise/sports 1-3 days/week)',
    moderate: 'Moderate Activity (moderate exercise/sports 3-5 days/week)',
    very: 'Very Active (hard exercise/sports 6-7 days a week)',
    extra: 'Extra Active (very hard exercise/sports & a physical job)',
    
    // Sorting and Filtering
    sortBy: 'Sort by',
    filterBy: 'Filter by',
    sortByName: 'Sort by Name',
    sortByAge: 'Sort by Age',
    sortByWeight: 'Sort by Weight',
    sortByHeight: 'Sort by Height',
    sortByGoal: 'Sort by Goal',
    sortByActivity: 'Sort by Activity Level',
    sortByCalories: 'Sort by Calories',
    filterByGoal: 'Filter by Goal',
    filterByActivity: 'Filter by Activity Level',
    filterByAge: 'Filter by Age',
    filterByGender: 'Filter by Gender',
    allGoals: 'All Goals',
    allActivities: 'All Activities',
    allAges: 'All Ages',
    allGenders: 'All Genders',
    ascending: 'Ascending',
    descending: 'Descending',
    clearFilters: 'Clear Filters',
    applyFilters: 'Apply Filters',
    
    // Dashboard page
    welcomeToDashboard: 'Welcome to Your Dashboard',
    overviewOfPractice: 'Overview of your nutrition practice',
    liveData: 'Live Data',
    totalClients: 'Total Clients',
    menusCreated: 'Menus Created',
    chatSessions: 'Chat Sessions',
    weeklyActivity: 'Weekly Activity',
    quickActions: 'Quick Actions',
    commonTasks: 'Access your most common tasks quickly',
    recentActivity: 'Recent Activity',
    latestUpdates: 'Latest updates from your practice',
    createMenu: 'Create Meal Plan',
    generateNutritionPlan: 'Generate a nutrition plan',
    manageClients: 'Manage Clients',
    viewEditClients: 'View and edit client profiles',
    startChat: 'Start Chat',
    consultWithAI: 'Consult with AI assistant',
    recipeManagement: 'Recipe Management',
    browseRecipes: 'Browse and manage recipes',
    nutritionPlans: 'Nutrition Plans',
    managePlans: 'Manage client nutrition plans',
    menuoverview: 'Meal Plan Overview',
    consultations: 'Consultations',
    startFirstChat: 'Start Your First Chat',
    physicalStats: 'Physical Stats',
    nutritionTargets: 'Nutrition Targets',
    dietaryRestrictions: 'Dietary Restrictions',
    userPreferences: 'User Preferences',
    weightChange: 'Weight Change',
    activeMenus: 'Active Menus',
    totalMenus: 'Total Menus',
    contactInformation: 'Contact Information',
    heightCm: 'Height (cm)',
    goal: 'Goal',
    preferences: 'Preferences',

    // Client Management
    clientInformation: 'Client Information',
    overviewOfClient: 'Overview of your client information',
    activityLevel: 'Activity Level',
    notes: 'Notes',
    editInformation: 'Edit Information',
    clientSummary: 'Client Summary',
    kcal: 'kcal',
    noMenusYet: 'No meal plans yet',
    createFirstMenu: 'Create your first meal plan for this client',
    menusTotal: 'total',
    viewAllMenus: 'View All Meal Plans',
    chatSession: 'Chat Session',
    messages: 'messages',
    noChatHistory: 'No chat history',
    startConversationWith: 'Start a conversation with this client',
    chatSessionsTotal: 'chat session',
    viewAllChats: 'View All Chats',
    noRecentActivity: 'No recent activity',
    nutritionSummary: 'Nutrition Summary',
    noMenuDataAvailable: 'No meal plan data available',
    updateInfo: 'Update Info',
    addNewClient: 'Add New Client',
    clientCode: 'Client Code',
    clientName: 'Client Name',
    phoneNumber: 'Phone Number',
    birthDate: 'Birth Date',
    medicalConditions: 'Medical Conditions',
    allergies: 'Allergies',
    preferences: 'Preferences',
    emergencyContact: 'Emergency Contact',

    // Menu Management
    menuName: 'Meal Plan Name',
    menuDescription: 'Meal Plan Description',
    targetCalories: 'Target Calories',
    mealPlan: 'Meal Plan',
    breakfast: 'Breakfast',
    lunch: 'Lunch',
    dinner: 'Dinner',
    snacks: 'Snacks',
    totalNutrition: 'Total Nutrition',
    macroBreakdown: 'Macro Breakdown',
    micronutrients: 'Micronutrients',
    vitamins: 'Vitamins',
    minerals: 'Minerals',
    fiber: 'Fiber',
    sugar: 'Sugar',
    sodium: 'Sodium',
    potassium: 'Potassium',
    calculateNutrition: 'Calculate Nutrition',
    generateMenu: 'Generate Meal Plan',
    saveMenu: 'Save Meal Plan',
    loadMenu: 'Load Meal Plan',
    duplicateMenu: 'Duplicate Meal Plan',
    deleteMenu: 'Delete Meal Plan',
    printMenu: 'Print Meal Plan',
    shareMenu: 'Share Meal Plan',

    // Ingredient Portion Dialog
    setPortion: 'Set Portion Size',
    portionDialogDescription: 'Enter the amount in grams and a household measurement. The nutrition values will be automatically adjusted based on the 100g serving size from the database.',
    amountInGrams: 'Amount (grams)',
    householdMeasure: 'Household Measure',
    householdMeasurePlaceholder: 'e.g., 1 cup, 2 tbsp, 1 medium apple',
    adjustedNutrition: 'Adjusted Nutrition',
    basedOn100g: 'Based on 100g serving',
    ratio: 'Ratio',
    pleaseFillAllFields: 'Please fill in all fields',
    pleaseEnterValidAmount: 'Please enter a valid amount greater than 0',
    editPortion: 'Edit portion size',
    ingredient: 'Ingredient',
    within5Percent: 'within ±5%',
    within10Percent: 'within ±10%',
    deleteIngredient: 'Delete ingredient',
    makeMain: 'Make Main',
    makeMainTooltip: 'Make this the main option',

    // Analytics & Reporting
    analyticsOverview: 'Analytics Overview',
    clientProgress: 'Client Progress',
    nutritionTrends: 'Nutrition Trends',
    goalAchievement: 'Goal Achievement',
    complianceRate: 'Compliance Rate',
    weeklyReport: 'Weekly Report',
    monthlyReport: 'Monthly Report',
    customReport: 'Custom Report',
    exportReport: 'Export Report',
    generateReport: 'Generate Report',
    reportPeriod: 'Report Period',
    dateRange: 'Date Range',
    fromDate: 'From Date',
    toDate: 'To Date',
    
    // API & Data Management
    apiConfiguration: 'API Configuration',
    dataImport: 'Data Import',
    dataExport: 'Data Export',
    syncData: 'Sync Data',
    backupData: 'Backup Data',
    restoreData: 'Restore Data',
    apiKey: 'API Key',
    apiEndpoint: 'API Endpoint',
    connectionStatus: 'Connection Status',
    connected: 'Connected',
    disconnected: 'Disconnected',
    lastSync: 'Last Sync',
    syncInProgress: 'Sync in Progress',
    
    // Recipes page
    healthyDeliciousRecipes: 'Healthy & Delicious Recipes',
    professionalRecipes: 'Professional nutrition recipes curated by experts for optimal health and taste',
    professionalRecipesDescription: 'Professional nutrition recipes curated by experts for optimal health and taste',
    recipesAvailable: '120+ Recipes',
    recipesCount: '120+ Recipes',
    expertApproved: 'Expert Approved',
    professionalRecipeCount: 'professional recipe',
    professionalRecipe: 'professional recipe',
    pluralSuffix: 's',
    serving: 'serving',
    salads: 'Salads',
    warmDishes: 'Warm Dishes',
    appetizers: 'Appetizers',
    more: 'More',
    howToMakeIt: 'How to make it',
    tip: 'Tip',
    printRecipe: 'Print Recipe',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    healthy: 'Healthy',
    quick: 'Quick',
    vegetarian: 'Vegetarian',
    vegan: 'Vegan',
    glutenFree: 'Gluten Free',
    dairyFree: 'Dairy Free',
    lowCarb: 'Low Carb',
    highProtein: 'High Protein',
    mediterranean: 'Mediterranean',
    fiberRich: 'Fiber Rich',
    comfortFood: 'Comfort Food',
    makeAhead: 'Make Ahead',
    mealPrep: 'Meal Prep',
    translating: 'Translating...',
    translateRecipes: 'Translate Recipes',
    translatingRecipes: 'Translating recipes...',
    recipeDifficulty: 'Difficulty',
    recipeTime: 'Time',
    recipeServings: 'Servings',
    recipeIngredients: 'Ingredients',
    recipeInstructions: 'Instructions',
    recipeTips: 'Tips',
    recipeMacros: 'Nutrition Facts',
    closeRecipe: 'Close Recipe',

    // Weight Logs page
    weightLogsDescription: 'Track and analyze client progress with comprehensive measurement data and beautiful visualizations',
    selectClient: 'Select Client',
    dateRange: 'Date Range',
    searchPlaceholder: 'Search measurements...',
    chartType: 'Chart Type',
    selectMetrics: 'Select Metrics to Display',
    progressChart: 'Progress Chart',
    progressChartDescription: 'Visual representation of client progress over time',
    refresh: 'Refresh',
    export: 'Export',
    loadingData: 'Loading data...',
    measurementHistory: 'Measurement History',
    measurementHistoryDescription: 'Detailed view of all measurements',
    totalMeasurements: 'Total Measurements',
    currentWeight: 'Current Weight',
    bodyFatPercent: 'Body Fat %',
    avgWeight: 'Avg Weight',
    periodAverage: 'Period average',
    noDataAvailableForFilters: 'No data available for the selected filters',
    pleaseSelectClientToView: 'Please select a client to view their weight logs',
    noWeightLogsFound: 'No weight logs found for the selected client',
    tryDifferentClientOrDateRange: 'Try selecting a different client or adjusting the date range',
    last7Days: 'Last 7 days',
    last30Days: 'Last 30 days',
    last90Days: 'Last 90 days',
    lastYear: 'Last year',
    allTime: 'All time',
    lineChart: 'Line Chart',
    areaChart: 'Area Chart',
    barChart: 'Bar Chart',
    weightKg: 'משקל (ק״ג)',
    bodyFatPercentage: 'Body Fat %',
    waistCm: 'Waist (cm)',
    hipCm: 'Hip (cm)',
    armCm: 'Arm (cm)',

    // Menu Create page
    createNewMenu: 'Create New Meal Plan',
    menuCreationWizard: 'Meal Plan Creation Wizard',
    buildNutritionPlan: 'Build a comprehensive nutrition plan for your client',
    menuBasics: 'Meal Plan Basics',
    clientSelection: 'Client Selection',
    selectTargetClient: 'Select the target client for this meal plan',
    noClientSelectedMenu: 'No client selected',
    menuNameLabel: 'Meal Plan Name',
    menuNamePlaceholder: 'Enter a descriptive name for this meal plan',
    menuDescriptionLabel: 'Meal Plan Description',
    menuDescriptionPlaceholder: 'Describe the purpose and goals of this meal plan',
    targetCaloriesLabel: 'Target Daily Calories',
    targetCaloriesPlaceholder: 'Enter target calories (e.g., 2000)',
    menuDuration: 'Meal Plan Duration',
    singleDay: 'Single Day',
    threeDays: '3 Days',
    oneWeek: '1 Week',
    twoWeeks: '2 Weeks',
    oneMonth: '1 Month',
    mealStructure: 'Meal Structure',
    includedMeals: 'Included Meals',
    additionalOptions: 'Additional Options',
    includeSnacks: 'Include Snacks',
    includeDrinks: 'Include Drinks',
    includeSupplements: 'Include Supplements',
    dietaryRestrictions: 'Dietary Restrictions',
    allergiesAndRestrictions: 'Allergies & Restrictions',
    preferredCuisines: 'Preferred Cuisines',
    menuGeneration: 'Meal Plan Generation',
    generateMenuAI: 'Generate Meal Plan with AI',
    generateMenuDescription: 'Click the button below to generate a personalized meal plan based on your preferences.',
    selected: 'Selected',
    dailyTotals: 'Daily Totals',
    manualMenuCreation: 'Manual Meal Plan Creation',
    nutritionTargets: 'Nutrition Targets',
    proteinTarget: 'Protein Target',
    carbsTarget: 'Carbohydrates Target',
    fatTarget: 'Fat Target',
    fiberTarget: 'Fiber Target',
    reviewAndSave: 'Review & Save',
    previewMenu: 'Preview Meal Plan',
    saveMenuDraft: 'Save as Draft',
    publishMenu: 'Publish Meal Plan',
    backToMenus: 'Back to Meal Plans',
    fromDatabase: "from database",
    targetVsGenerated: "Target vs Generated Meal Plan Comparison",
    target: "Target",
    generated: "Generated",
    difference: "Difference",
    menuAccuracy: "Meal Plan Accuracy",
    accurate: "Accurate",
    within5Percent: "within ±5%",
    noTargetDataFound: "No target data found for this client.",
    addingProductCodes: "Adding product codes to ingredients...",
    personalizedRecommendations: "Personalized recommendations",
    generalComments: "General Comments",
    confirmClearMenu: "Are you sure you want to clear the current meal plan and start fresh? This action cannot be undone.",
    startFresh: "Start Fresh",
    previousMenuFound: "Previous Meal Plan Found",
    previousMenuDescription: "We found a previously generated meal plan for",
    fromTime: "from",
    continueOrStartFresh: "Would you like to continue working on it or start fresh?",
    continuePreviousMenu: "Continue Previous Meal Plan",
    loadingClientTargets: "Loading client targets...",
    mainOption: "Main Option",
    alternative: "Alternative",
    otherAlternatives: "Other Alternatives",
    addAlternative: "Add Alternative",
    downloadAsPdf: "Download as PDF",
    upcCache: "UPC Cache",
    ingredientsStored: "ingredients stored",
    upcCacheCleared: "UPC cache cleared successfully!",
    clearCache: "Clear Cache",
    menuAutoSaved: "Meal plan auto-saved locally",
    saveSchemaAndMenu: "Save Schema & Meal Plan",
    showShoppingList: "Show Shopping List",
    hideShoppingList: "Hide Shopping List",

    // Menu Load page specific translations
    editMenu: 'Edit Meal Plan',
    loadedMenu: 'Loaded Meal Plan',
    searchMenus: 'Search by name or client code...',
    filterByClient: 'Filter by client',
    allClients: 'All Clients',
    checkExpiredMenus: 'Check Expired Meal Plans',
    checking: 'Checking...',
    untitledMenu: 'Untitled Meal Plan',
    notAvailable: 'N/A',
    created: 'Created',
    updated: 'Updated',
    activeFrom: 'Active From',
    activeUntil: 'Active Until',
    loadAndEditMenu: 'Load & Edit Meal Plan',
    manageStatus: 'Manage Status',
    noMenusFound: 'No meal plans found',
    noMenusMatchCriteria: 'No meal plans match your search criteria',
    manageMenuStatus: 'Manage Meal Plan Status',
    status: 'Status',
    optional: 'Optional',
    updating: 'Updating...',
    updateStatus: 'Update Status',
    deleteIngredient: 'Delete ingredient',
    mainOption: 'Main Option',
    alternativeOption: 'Alternative Option',
    otherAlternatives: 'Other Alternatives',
    generating: 'Generating...',
    addAlternative: 'Add Alternative',
    makeMain: 'Make Main',
    saving: 'Saving...',
    saveChanges: 'Save Changes',

    // Menu Load page
    loadExistingMenu: 'Load Existing Meal Plan',
    browseMenuLibrary: 'Browse Meal Plan Library',
    loadMenu: 'Load Meal Plan',
    duplicateAndEdit: 'Duplicate & Edit',
    menuPreview: 'Meal Plan Preview',
    menuCreatedBy: 'Created by',
    menuCreatedDate: 'Created',
    menuLastModified: 'Last Modified',
    menuUsageCount: 'Used',
    menuRating: 'Rating',
    noMenusAvailable: 'No meal plans available',
    menuCode: 'Meal Plan Code',
    createYourFirstMenu: 'Create your first meal plan',
    loadSelectedMenu: 'Load Selected Meal Plan',
    menuLoadSuccess: 'Meal plan loaded successfully',
    menuLoadError: 'Failed to load meal plan',

    // User Management page
    userManagementTitle: 'User Management',
    allUsers: 'All Users',
    activeUsers: 'Active Users',
    inactiveUsers: 'Inactive Users',
    newUsers: 'New Users',
    addNewUser: 'Add New User',
    userProfile: 'User Profile',
    userDetails: 'User Details',
    personalInformation: 'Personal Information',
    contactInformation: 'Contact Information',
    healthInformation: 'Health Information',
    firstName: 'First Name',
    lastName: 'Last Name',
    fullName: 'Full Name',
    dateOfBirth: 'Date of Birth',
    emailAddress: 'Email Address',
    phoneNumberField: 'Phone Number',
    address: 'Address',
    city: 'City',
    state: 'State',
    zipCode: 'Zip Code',
    country: 'Country',
    emergencyContactName: 'Emergency Contact Name',
    emergencyContactPhone: 'Emergency Contact Phone',
    relationship: 'Relationship',
    currentWeight: 'Current Weight',
    goalWeight: 'Goal Weight',
    heightField: 'Height',
    bodyFatPercentage: 'Body Fat Percentage',
    medicalHistory: 'Medical History',
    currentMedications: 'Current Medications',
    dietaryAllergies: 'Dietary Allergies',
    foodIntolerances: 'Food Intolerances',
    dietaryPreferences: 'Dietary Preferences',
    fitnessLevel: 'Fitness Level',
    exerciseFrequency: 'Exercise Frequency',
    dailyActivityLevel: 'Daily Activity Level',
    healthGoals: 'Health Goals',
    nutritionGoals: 'Nutrition Goals',
    userStatus: 'User Status',
    activeStatus: 'Active',
    inactiveStatus: 'Inactive',
    pendingStatus: 'Pending',
    suspendedStatus: 'Suspended',
    registrationDate: 'Registration Date',
    lastLoginDate: 'Last Login',
    totalSessions: 'Total Sessions',
    userActions: 'User Actions',
    viewProfile: 'View Profile',
    editProfile: 'Edit Profile',
    deleteUser: 'Delete User',
    suspendUser: 'Suspend User',
    activateUser: 'Activate User',
    resetPassword: 'Reset Password',
    sendMessage: 'Send Message',
    exportUserData: 'Export User Data',
    userSearchPlaceholder: 'Search by name, email, or ID...',
    filterByStatus: 'Filter by Status',
    filterByDate: 'Filter by Date',
    sortByName: 'Sort by Name',
    sortByDate: 'Sort by Date',
    sortByActivity: 'Sort by Activity',
    
    // Nutrition Plan
    searchIngredient: 'Search ingredient...',
    editPlan: 'Edit Plan',
    personalizedNutritionPlan: 'Personalized Nutrition Plan',
    addMeal: 'Add Meal',
    addItem: 'Add Item',
    addIngredient: 'Add Ingredient',
    mealName: 'Meal Name',
    itemName: 'Item Name',
    portion: 'Portion',
    protein: 'Protein',
    fat: 'Fat',
    energy: 'Energy',
    calories: 'kcal',
    nutritionValues: 'Nutrition Values',
    ingredients: 'Ingredients',
    alternatives: 'Alternatives',
    overview: 'Overview',
    meals: 'Meals',
    nutrition: 'Nutrition',
    recommendations: 'Recommendations',
    clientInfo: 'Client Information',
    name: 'Name',
    age: 'Age',
    height: 'Height',
    weight: 'Weight',
    dailyNutrition: 'Daily Nutrition',
    carbs: 'Carbs',
    supplements: 'Supplements',
    hydration: 'Hydration',
    sleep: 'Sleep',
    general: 'General',
    
    // Settings & Configuration
    accountSettings: 'Account Settings',
    profileSettings: 'Profile Settings',
    notificationSettings: 'Notification Settings',
    privacySettings: 'Privacy Settings',
    appearanceSettings: 'Appearance Settings',
    languageSettings: 'Language Settings',
    themeSettings: 'Theme Settings',
    emailNotifications: 'Email Notifications',
    pushNotifications: 'Push Notifications',
    dataRetention: 'Data Retention',
    twoFactorAuth: 'Two-Factor Authentication',
    passwordChange: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',

    // Forms & Validation
    required: 'Required',
    optional: 'Optional',
    pleaseEnter: 'Please enter',
    pleaseSelect: 'Please select',
    invalidEmail: 'Invalid email address',
    passwordTooShort: 'Password too short',
    passwordsDoNotMatch: 'Passwords do not match',
    fieldRequired: 'This field is required',
    invalidFormat: 'Invalid format',
    valueTooLow: 'Value too low',
    valueTooHigh: 'Value too high',
    invalidPhoneNumber: 'Invalid phone number',
    invalidDate: 'Invalid date',
    futureDate: 'Date cannot be in the future',
    pastDate: 'Date cannot be in the past',

    // Status Messages
    success: 'Success',
    error: 'Error',
    warning: 'Warning',
    info: 'Information',
    saved: 'Saved',
    updated: 'Updated',
    deleted: 'Deleted',
    created: 'Created',
    imported: 'Imported',
    exported: 'Exported',
    synchronized: 'Synchronized',
    published: 'Published',
    unpublished: 'Unpublished',
    activated: 'Activated',
    deactivated: 'Deactivated',
    processing: 'Processing',
    completed: 'Completed',
    failed: 'Failed',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    inProgress: 'In Progress',
    cancelled: 'Cancelled',

    // Data Display
    noDataAvailable: 'No data available',
    noResultsFound: 'No results found',
    emptyList: 'Empty list',
    showMore: 'Show More',
    showLess: 'Show Less',
    viewAll: 'View All',
    viewDetails: 'View Details',
    sortBy: 'Sort by',
    filterBy: 'Filter by',
    groupBy: 'Group by',
    ascending: 'Ascending',
    descending: 'Descending',
    firstPage: 'First Page',
    lastPage: 'Last Page',
    itemsPerPage: 'Items per Page',
    showingItems: 'Showing',
    of: 'of',
    total: 'Total',
    selected: 'Selected',
    all: 'All',
    none: 'None',

    // Chat & Communication
    typeMessage: 'Type a message...',
    sendMessage: 'Send Message',
    chatHistory: 'Chat History',
    conversationStarted: 'Conversation Started',
    messageDelivered: 'Message Delivered',
    messageRead: 'Message Read',
    onlineStatus: 'Online',
    offlineStatus: 'Offline',
    lastSeen: 'Last seen',
    typing: 'Typing...',
    attachFile: 'Attach File',
    sendImage: 'Send Image',
    voiceMessage: 'Voice Message',
    videoCall: 'Video Call',
    loadingMore: 'Loading more messages...',
    loadMore: 'Load more messages',

    // Profile & Professional Info
    specialization: 'Specialization',
    certification: 'Certification',
    yearsOfExperience: 'Years of Experience',
    clinicName: 'Clinic Name',
    clinicAddress: 'Clinic Address',
    profileBio: 'Profile Bio',
    languages: 'Languages',
    consultationFee: 'Consultation Fee',
    availableTimes: 'Available Times',
    professionalTitle: 'Professional Title',
    licenseNumber: 'License Number',
    educationBackground: 'Education Background',
    workExperience: 'Work Experience',
    achievements: 'Achievements',
    publications: 'Publications',
  },
  he: {
    // Navigation & Main Pages
    home: 'לוח בקרה',
    dashboard: 'לוח בקרה',
    about: 'אודות',
    services: 'שירותים',
    contact: 'צור קשר',
    chat: 'צ\'אט',
    allChats: 'כל הצ\'אטים',
    dataGenerator: 'יצירת נתונים',
    nutritionPlan: 'תוכנית תזונה',
    menuCreate: 'יצירת תוכנית ארוחות',
    menuEdit: 'עריכת תוכנית ארוחות',
    menuView: 'צפייה בתוכנית ארוחות',
    menuLoad: 'טעינת תוכנית ארוחות',
    menuAnalysis: 'ניתוח תוכנית ארוחות',
    menus: 'תוכניות ארוחות',
    apiMenus: 'תוכניות ארוחות API',
    clients: 'לקוחות',
    clientProfile: 'פרופיל לקוח',
    clientMenu: 'תוכנית ארוחות לקוח',
    apiClientMenu: 'תוכנית ארוחות לקוח API',
    editClient: 'עריכת לקוח',
    users: 'משתמשים',
    recipes: 'מתכונים',
    recipesPage: 'מתכונים',
    weightLogs: 'יומן משקל',
    menuload: 'טעינת תוכנית ארוחות',
    settings: 'הגדרות',
    register: 'הרשמה',
    login: 'התחברות',
    
    // Common buttons and labels
    submit: 'שלח',
    cancel: 'ביטול',
    save: 'שמור',
    delete: 'מחק',
    signOut: 'התנתק',
    retry: 'נסה שוב',
    edit: 'ערוך',
    loading: 'טוען...',
    search: 'חפש',
    close: 'סגור',
    open: 'פתח',
    next: 'הבא',
    previous: 'הקודם',
    send: 'שלח',
    upload: 'העלה',
    download: 'הורד',
    settings: 'הגדרות',
    profile: 'פרופיל',
    back: 'חזור',
    continue: 'המשך',
    confirm: 'אשר',
    yes: 'כן',
    no: 'לא',
    
    // Client selection
    selectClient: 'בחר לקוח',
    
    // Language switch
    switchLanguage: 'English',
    
    // Error messages
    connectionError: 'שגיאת התחברות',
    failedToLoad: 'טעינת נתוני המשתמש נכשלה. אנא רענן את הדף.',
    
    // Chat page
    selectClientToChat: 'בחר לקוח לשיחה',
    chooseClientFromList: 'בחר לקוח מהרשימה שלך כדי להתחיל לצ\'אט',
    selectAClient: 'בחר לקוח...',
    chatWith: 'צ\'אט עם',
    clientCode: 'קוד לקוח',
    dailyCalories: 'קלוריות יומיות',
    notSet: 'לא נקבע',
    startConversation: 'התחל שיחה',
    chatAboutNutrition: 'על תוכנית התזונה שלהם. תוכל גם לשתף תמונות אוכל לניתוח.',
    noClientSelected: 'לא נבחר לקוח',
    selectClientToStart: 'אנא בחר לקוח מהתפריט הנפתח למעלה כדי להתחיל לצ\'אט על תוכנית התזונה שלהם.',
    messageClient: 'הודעה ל',
    imageSelected: 'תמונה נבחרה',
    uploadedFood: 'אוכל שהועלה',
    failedToUpload: 'העלאת התמונה נכשלה. אנא נסה שוב.',
    failedToSend: 'שליחת ההודעה נכשלה. אנא נסה שוב.',
    failedToLoadClients: 'טעינת הלקוחות נכשלה. אנא נסה שוב מאוחר יותר.',
    failedToLoadClientData: 'טעינת נתוני הלקוח נכשלה. אנא נסה שוב מאוחר יותר.',
    
    // Login page
    login: 'התחברות',
    enterCredentials: 'הכנס את פרטי הגישה שלך כדי לגשת לחשבון שלך',
    email: 'אימייל',
    enterEmail: 'הכנס את האימייל שלך',
    password: 'סיסמה',
    enterPassword: 'הכנס את הסיסמה שלך',
    signIn: 'התחבר',
    signingIn: 'מתחבר...',
    dontHaveAccount: 'אין לך חשבון?',
    register: 'הרשמה',
    failedToSignIn: 'ההתחברות נכשלה. אנא בדוק את פרטי הגישה שלך ונסה שוב.',
    
    // Users page
    userManagement: 'ניהול משתמשים',
    manageUserProfiles: 'נהל פרופילי משתמשים ומידע תזונתי',
    searchUsers: 'חפש משתמשים...',
    users: 'משתמשים',
    viewAndManageUsers: 'צפה ונהל את כל המשתמשים הרשומים',
    userCode: 'קוד משתמש',
    details: 'פרטים',
    actions: 'פעולות',
    noData: 'אין נתונים',
    noUsersFound: 'לא נמצאו משתמשים',
    editUserInformation: 'ערוך מידע משתמש',
    editUserDescription: 'עדכן את מידע הלקוח והעדפותיו.',
    addUserDescription: 'הוסף לקוח חדש למרפאה שלך.',
    heightCm: 'גובה (סמ)',
    weightKg: 'משקל (ק״ג)',
    gender: 'מין',
    activity: 'פעילות',
    goal: 'מטרה',
    selectGender: 'בחר מין',
    male: 'זכר',
    female: 'נקבה',
    selectActivityLevel: 'בחר רמת פעילות',
    sedentary: 'יושב (אין או מעט מאוד פעילות גופנית)',
    lightActivity: 'פעילות קלה (פעילות גופנית קלה/ספורט 1-3 ימים בשבוע)',
    moderateActivity: 'פעילות בינונית (פעילות גופנית בינונית/ספורט 3-5 ימים בשבוע)',
    veryActive: 'פעיל מאוד (פעילות גופנית קשה/ספורט 6-7 ימים בשבוע)',
    extraActive: 'פעיל במיוחד (פעילות גופנית קשה מאוד/ספורט ועבודה פיזית)',
    selectGoal: 'בחר מטרה',
    loseWeight: 'הורדת משקל',
    maintainWeight: 'שמירת משקל',
    gainWeight: 'עלייה במשקל',
    saveChanges: 'שמור שינויים',
    clientManagement: 'ניהול לקוחות',
    manageClientProfiles: 'נהל את פרופילי הלקוחות שלך ומידע',
    addNewClient: 'הוסף לקוח חדש',
    searchClients: 'חפש לקוחות על פי שם, אימייל, קוד או טלפון...',
    clients: 'לקוחות',
    viewAndManageClients: 'צפה ונהל את פרופילי הלקוחות שלך',
    showAll: 'הצג הכל',
    showLess: 'הצג פחות',
    of: 'מתוך',
    noClientsFound: 'לא נמצאו לקוחות שעונים על חיפוש שלך',
    noClientsFoundGeneral: 'לא נמצאו לקוחות. הוסף את הלקוח הראשון שלך כדי להתחיל.',
    contact: 'צור קשר',
    physical: 'גופני',
    goals: 'מטרות',
    macros: 'מאקרו',
    name: 'שם',
    yearsOld: 'שנים',
    city: 'עיר',
    noDataAvailable: 'אין נתונים',
    invalidBmiData: 'נתוני BMI שגויים',
    activityLevel: 'רמת פעילות',
    activity: 'פעילות',
    kcalPerDay: 'קק״ל/יום',
    noMacrosSet: 'מאקרו לא נקבע',
    basicInformation: 'מידע בסיסי',
    clientCode: 'קוד לקוח',
    fullName: 'שם מלא',
    email: 'אימייל',
    phoneNumber: 'מספר טלפון',
    dateOfBirth: 'תאריך לידה',
    physicalInformation: 'מידע גופני',
    age: 'גיל',
    weight: 'משקל',
    height: 'גובה',
    other: 'אחר',
    toning: 'טינינג',
    buildMuscle: 'בניית שריר',
    improveHealth: 'שיפור בריאות',
    nutritionInformation: 'מידע תזונתי',
    dailyTotalCalories: 'קלוריות כוללות יומיות',
    autoCalculated: 'מחושב אוטומטית',
    harrisBenedictInfo: 'מבוסס על נוסחת האריס-בנדיקט באמצעות גיל, מין, משקל, גובה, רמת פעילות ומטרה',
    mifflinStJeorInfo: 'מבוסס על נוסחת מיפלין-סנט ג\'ור באמצעות גיל, מין, משקל, גובה, רמת פעילות ומטרה',
    fillRequiredFieldsToCalculate: 'מלא שדות נדרשים לחישוב',
    isRequired: 'נדרש',
    ageCalculatedFromBirthDate: 'גיל מחושב מתאריך לידה',
    enterAgeOrBirthDate: 'הכנס גיל או תאריך לידה',
    numberOfMeals: 'מספר הארוחות',
    region: 'אזור',
    macrosGrams: 'מאקרו (גרמים)',
    protein: 'חלבון',
    calories: 'קלוריות',
    ingredients: 'מרכיבים',
    carbs: 'פחמימות',
    fat: 'שומן',
    grams: 'גרם',
    totalPercentages: 'סה״כ אחוזים',
    totalCaloriesInTargets: 'סה״כ קלוריות ביעדים',
    macrosSumMatches: 'סכום המאקרו תמיד תואם את הקלוריות:',
    caloriesFormula: 'קלוריות = (4 × חלבון) + (4 × פחמימות) + (9 × שומן)',
    dietaryInformation: 'מידע תזונתי',
    foodAllergies: 'אלרגיות במזון',
    foodAllergiesPlaceholder: 'למשל, פרי עץ, חלב, ביצים (סוגרי ברירה עם פסיקים)',
    foodLimitations: 'הגבלות במזון',
    foodLimitationsPlaceholder: 'טקסט פשוט: צמחוני, קושר, נמוך בנתרן',
    foodLimitationsHelp: '✨ הכנס טקסט פשוט כמו "צמחוני, קושר" והוא יתמיר בעצמו ל["צמחוני", "קושר"]',
    clientPreferences: 'העדפות לקוח',
    foodDiary: 'יומן מזון',
    clientPreferencesPlaceholder: 'טקסט פשוט: אוהב פסטה, מטבח ים תיכוני, ארוחות מהירות',
    clientPreferencesHelp: '✨ הכנס טקסט פשוט כמו "אוהב פסטה" והוא יתמיר בעצמו ל["אוהב פסטה"]',
    recommendations: 'המלצות',
    recommendationsPlaceholder: 'טקסט פשוט: שתה יותר מים, קח ויטמין D, תרגיל 30דקות יומיות',
    recommendationsHelp: '✨ הכנס טקסט פשוט והוא יתמיר בעצמו להמלצות מבנוות',
    saving: 'שמירה...',
    updateClient: 'עדכן לקוח',
    addClient: 'הוסף לקוח',
    failedToLoadClients: 'טעינת הלקוחות נכשלה. אנא נסה שוב.',
    failedToSaveClient: 'שמירת הלקוח נכשלה:',
    failedToUpdateClient: 'עדכון הלקוח נכשל:',
    failedToCreateClient: 'יצירת הלקוח נכשל:',
    failedToDeleteClient: 'נכשל מחיקת הלקוח',
    confirmDelete: 'האם אתה בטוח שברצונך למחוק',
    clientDeleted: 'הלקוח נמחק בהצלחה',
    deleteWarning: 'פעולה זו לא ניתנת לביטול.',
    foodLogsFound: 'נמצאו יומני מזון',
    entriesFound: 'רשומות נמצאו',
    preferencesAutoPopulated: 'העדפות מולאו אוטומטית',
    autoPopulated: 'מולא אוטומטית',
    translateToHebrew: 'תרגם לעברית',
    viewDetailedAnalysis: 'צפה בניתוח תזונתי מפורט',
    detailedAnalysis: 'ניתוח תזונתי מפורט',
    comprehensiveAnalysis: 'ניתוח מקיף של הרגלי האכילה של הלקוח עם המלצות לשיפור',
    analysisSummary: 'סיכום הניתוח',
    totalEntries: 'סה״כ רשומות',
    uniqueFoods: 'מזונות ייחודיים',
    mealCategories: 'קטגוריות ארוחות',
    analysisDate: 'תאריך הניתוח',
    topFoodsByMeal: 'מזונות מובילים לפי קטגוריית ארוחה',
    times: 'פעמים',
    aiDietitianPrompt: 'פקודת ניתוח דיאטנית AI',
    nutritionalAnalysis: 'ניתוח תזונתי',
    analysisDescription: 'ניתוח שנוצר על ידי AI של הרגלי האכילה של הלקוח עם המלצות מותאמות אישית לשיפור.',
    copySystemPrompt: 'העתק פקודת מערכת',
    copyAnalysis: 'העתק ניתוח',
    systemPromptCopied: 'פקודת המערכת הועתקה ללוח!',
    analysisCopied: 'הניתוח הועתק ללוח!',
    
    // BMI Status
    underweight: 'תת משקל',
    normal: 'נורמלי',
    overweight: 'תמוסף',
    obese: 'שמנה',
    
    // Goal values
    lose: 'הורדת משקל',
    maintain: 'שמירת משקל',
    gain: 'עלייה במשקל',
    muscle: 'בניית שריר',
    health: 'שיפור בריאות',
    
    // Activity values
    sedentary: 'יושב (אין או מעט מאוד פעילות גופנית)',
    light: 'פעילות קלה (פעילות גופנית קלה/ספורט 1-3 ימים בשבוע)',
    moderate: 'פעילות בינונית (פעילות גופנית בינונית/ספורט 3-5 ימים בשבוע)',
    very: 'פעיל מאוד (פעילות גופנית קשה/ספורט 6-7 ימים בשבוע)',
    extra: 'פעיל במיוחד (פעילות גופנית קשה מאוד/ספורט ועבודה פיזית)',
    
    // Sorting and Filtering
    sortBy: 'מיון לפי',
    filterBy: 'סינון לפי',
    sortByName: 'מיון לפי שם',
    sortByAge: 'מיון לפי גיל',
    sortByWeight: 'מיון לפי משקל',
    sortByHeight: 'מיון לפי גובה',
    sortByGoal: 'מיון לפי מטרה',
    sortByActivity: 'מיון לפי רמת פעילות',
    sortByCalories: 'מיון לפי קלוריות',
    filterByGoal: 'סינון לפי מטרה',
    filterByActivity: 'סינון לפי רמת פעילות',
    filterByAge: 'סינון לפי גיל',
    filterByGender: 'סינון לפי מין',
    allGoals: 'כל המטרות',
    allActivities: 'כל הפעילויות',
    allAges: 'כל הגילאים',
    allGenders: 'כל המינים',
    ascending: 'ממוין בסדר עולה',
    descending: 'ממוין בסדר יורד',
    clearFilters: 'נקה סינונים',
    applyFilters: 'החל סינונים',
    
    // Dashboard page
    welcomeToDashboard: 'ברוכים הבאים ללוח הבקרה שלכם',
    overviewOfPractice: 'סקירה כללית של המרפאה התזונתית שלכם',
    liveData: 'נתונים בזמן אמת',
    totalClients: 'סה״כ לקוחות',
    menusCreated: 'תפריטים שנוצרו',
    chatSessions: 'סשני צ\'אט',
    weeklyActivity: 'פעילות שבועית',
    quickActions: 'פעולות מהירות',
    commonTasks: 'גישה מהירה למשימות הנפוצות שלכם',
    recentActivity: 'פעילות אחרונה',
    latestUpdates: 'עדכונים אחרונים מהמרפאה שלכם',
    createMenu: 'צור תוכנית ארוחות',
    generateNutritionPlan: 'יצירת תוכנית תזונה',
    manageClients: 'ניהול לקוחות',
    viewEditClients: 'צפייה ועריכת פרופילי לקוחות',
    startChat: 'התחל צ\'אט',
    consultWithAI: 'התייעצות עם עוזר בינה מלאכותית',
    recipeManagement: 'ניהול מתכונים',
    browseRecipes: 'עיון וניהול מתכונים',
    nutritionPlans: 'תוכניות תזונה',
    managePlans: 'ניהול תוכניות תזונה ללקוחות',
    menuoverview: 'תצוגה כללית של תוכנית ארוחות',
    consultations: 'התייעצויות',
    startFirstChat: 'התחל את הצ\'אט הראשון שלך',
    physicalStats: 'סטטיסטיקות גופניות',
    nutritionTargets: 'יעדי תזונה',
    dietaryRestrictions: 'הגבלות תזונתיות',
    userPreferences: 'העדפות משתמש',
    weightChange: 'שינוי משקל',
    activeMenus: 'תפריטים פעילים',
    totalMenus: 'סה״כ תפריטים',
    contactInformation: 'מידע ליצירת קשר',
    heightCm: 'גובה (סמ)',
    goal: 'מטרה',
    preferences: 'העדפות',

    // Client Management
    clientInformation: 'מידע לקוח',
    overviewOfClient: 'סקירה כללית של מידע הלקוח שלך',
    activityLevel: 'רמת פעילות',
    notes: 'הערות',
    editInformation: 'ערוך מידע',
    clientSummary: 'סיכום לקוח',
    kcal: 'קק״ל',
    noMenusYet: 'אין תוכניות ארוחות עדיין',
    createFirstMenu: 'צור את תוכנית הארוחות הראשונה שלך עבור הלקוח הזה',
    menusTotal: 'סה״כ',
    viewAllMenus: 'צפה בכל תוכניות הארוחות',
    chatSession: 'סשן צ\'אט',
    messages: 'הודעות',
    noChatHistory: 'אין היסטוריית צ\'אט',
    startConversationWith: 'התחל שיחה עם הלקוח הזה',
    chatSessionsTotal: 'סשן צ\'אט',
    viewAllChats: 'צפה בכל הצ\'אטים',
    noRecentActivity: 'אין פעילות אחרונה',
    nutritionSummary: 'סיכום תזונתי',
    noMenuDataAvailable: 'אין נתוני תוכנית ארוחות זמינים',
    updateInfo: 'עדכן מידע',
    addNewClient: 'הוסף לקוח חדש',
    clientCode: 'קוד לקוח',
    clientName: 'Client Name',
    phoneNumber: 'Phone Number',
    birthDate: 'Birth Date',
    medicalConditions: 'Medical Conditions',
    allergies: 'Allergies',
    preferences: 'Preferences',
    emergencyContact: 'Emergency Contact',

    // Menu Management
    menuName: 'שם תוכנית ארוחות',
    menuDescription: 'תיאור תוכנית ארוחות',
    targetCalories: 'קלוריות יעד',
    mealPlan: 'תוכנית ארוחות',
    breakfast: 'ארוחת בוקר',
    lunch: 'ארוחת צהריים',
    dinner: 'ארוחת ערב',
    snacks: 'חטיפים',
    totalNutrition: 'Total Nutrition',
    macroBreakdown: 'Macro Breakdown',
    micronutrients: 'Micronutrients',
    vitamins: 'Vitamins',
    minerals: 'Minerals',
    fiber: 'Fiber',
    sugar: 'Sugar',
    sodium: 'Sodium',
    potassium: 'Potassium',
    calculateNutrition: 'Calculate Nutrition',
    generateMenu: 'Generate Meal Plan',
    saveMenu: 'Save Meal Plan',
    loadMenu: 'Load Meal Plan',
    duplicateMenu: 'Duplicate Meal Plan',
    deleteMenu: 'Delete Meal Plan',
    printMenu: 'Print Meal Plan',
    shareMenu: 'Share Meal Plan',

    // Ingredient Portion Dialog
    setPortion: 'Set Portion Size',
    portionDialogDescription: 'Enter the amount in grams and a household measurement. The nutrition values will be automatically adjusted based on the 100g serving size from the database.',
    amountInGrams: 'Amount (grams)',
    householdMeasure: 'Household Measure',
    householdMeasurePlaceholder: 'e.g., 1 cup, 2 tbsp, 1 medium apple',
    adjustedNutrition: 'Adjusted Nutrition',
    basedOn100g: 'Based on 100g serving',
    ratio: 'Ratio',
    pleaseFillAllFields: 'Please fill in all fields',
    pleaseEnterValidAmount: 'Please enter a valid amount greater than 0',
    editPortion: 'Edit portion size',
    ingredient: 'Ingredient',
    within5Percent: 'within ±5%',
    within10Percent: 'within ±10%',
    deleteIngredient: 'Delete ingredient',
    makeMain: 'Make Main',
    makeMainTooltip: 'Make this the main option',

    // Analytics & Reporting
    analyticsOverview: 'Analytics Overview',
    clientProgress: 'Client Progress',
    nutritionTrends: 'Nutrition Trends',
    goalAchievement: 'Goal Achievement',
    complianceRate: 'Compliance Rate',
    weeklyReport: 'Weekly Report',
    monthlyReport: 'Monthly Report',
    customReport: 'Custom Report',
    exportReport: 'Export Report',
    generateReport: 'Generate Report',
    reportPeriod: 'Report Period',
    dateRange: 'Date Range',
    fromDate: 'From Date',
    toDate: 'To Date',
    
    // API & Data Management
    apiConfiguration: 'API Configuration',
    dataImport: 'Data Import',
    dataExport: 'Data Export',
    syncData: 'Sync Data',
    backupData: 'Backup Data',
    restoreData: 'Restore Data',
    apiKey: 'API Key',
    apiEndpoint: 'API Endpoint',
    connectionStatus: 'Connection Status',
    connected: 'Connected',
    disconnected: 'Disconnected',
    lastSync: 'Last Sync',
    syncInProgress: 'Sync in Progress',
    
    // Recipes page
    healthyDeliciousRecipes: 'Healthy & Delicious Recipes',
    professionalRecipes: 'Professional nutrition recipes curated by experts for optimal health and taste',
    professionalRecipesDescription: 'Professional nutrition recipes curated by experts for optimal health and taste',
    recipesAvailable: '120+ Recipes',
    recipesCount: '120+ Recipes',
    expertApproved: 'Expert Approved',
    professionalRecipeCount: 'professional recipe',
    professionalRecipe: 'professional recipe',
    pluralSuffix: 's',
    serving: 'serving',
    salads: 'Salads',
    warmDishes: 'Warm Dishes',
    appetizers: 'Appetizers',
    more: 'More',
    howToMakeIt: 'How to make it',
    tip: 'Tip',
    printRecipe: 'Print Recipe',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    healthy: 'Healthy',
    quick: 'Quick',
    vegetarian: 'Vegetarian',
    vegan: 'Vegan',
    glutenFree: 'Gluten Free',
    dairyFree: 'Dairy Free',
    lowCarb: 'Low Carb',
    highProtein: 'High Protein',
    mediterranean: 'Mediterranean',
    fiberRich: 'Fiber Rich',
    comfortFood: 'Comfort Food',
    makeAhead: 'Make Ahead',
    mealPrep: 'Meal Prep',
    translating: 'Translating...',
    translateRecipes: 'Translate Recipes',
    translatingRecipes: 'Translating recipes...',
    recipeDifficulty: 'Difficulty',
    recipeTime: 'Time',
    recipeServings: 'Servings',
    recipeIngredients: 'Ingredients',
    recipeInstructions: 'Instructions',
    recipeTips: 'Tips',
    recipeMacros: 'Nutrition Facts',
    closeRecipe: 'Close Recipe',

    // Weight Logs page
    weightLogsDescription: 'Track and analyze client progress with comprehensive measurement data and beautiful visualizations',
    selectClient: 'Select Client',
    dateRange: 'Date Range',
    searchPlaceholder: 'Search measurements...',
    chartType: 'Chart Type',
    selectMetrics: 'Select Metrics to Display',
    progressChart: 'Progress Chart',
    progressChartDescription: 'Visual representation of client progress over time',
    refresh: 'Refresh',
    export: 'Export',
    loadingData: 'Loading data...',
    measurementHistory: 'Measurement History',
    measurementHistoryDescription: 'Detailed view of all measurements',
    totalMeasurements: 'Total Measurements',
    currentWeight: 'Current Weight',
    bodyFatPercent: 'Body Fat %',
    avgWeight: 'Avg Weight',
    periodAverage: 'Period average',
    noDataAvailableForFilters: 'No data available for the selected filters',
    pleaseSelectClientToView: 'Please select a client to view their weight logs',
    noWeightLogsFound: 'No weight logs found for the selected client',
    tryDifferentClientOrDateRange: 'Try selecting a different client or adjusting the date range',
    last7Days: 'Last 7 days',
    last30Days: 'Last 30 days',
    last90Days: 'Last 90 days',
    lastYear: 'Last year',
    allTime: 'All time',
    lineChart: 'Line Chart',
    areaChart: 'Area Chart',
    barChart: 'Bar Chart',
    weightKg: 'משקל (ק״ג)',
    bodyFatPercentage: 'Body Fat %',
    waistCm: 'Waist (cm)',
    hipCm: 'Hip (cm)',
    armCm: 'Arm (cm)',

    // Menu Create page
    createNewMenu: 'Create New Meal Plan',
    menuCreationWizard: 'Meal Plan Creation Wizard',
    buildNutritionPlan: 'Build a comprehensive nutrition plan for your client',
    menuBasics: 'Meal Plan Basics',
    clientSelection: 'Client Selection',
    selectTargetClient: 'Select the target client for this meal plan',
    noClientSelectedMenu: 'No client selected',
    menuNameLabel: 'Meal Plan Name',
    menuNamePlaceholder: 'Enter a descriptive name for this meal plan',
    menuDescriptionLabel: 'Meal Plan Description',
    menuDescriptionPlaceholder: 'Describe the purpose and goals of this meal plan',
    targetCaloriesLabel: 'Target Daily Calories',
    targetCaloriesPlaceholder: 'Enter target calories (e.g., 2000)',
    menuDuration: 'Meal Plan Duration',
    singleDay: 'Single Day',
    threeDays: '3 Days',
    oneWeek: '1 Week',
    twoWeeks: '2 Weeks',
    oneMonth: '1 Month',
    mealStructure: 'Meal Structure',
    includedMeals: 'Included Meals',
    additionalOptions: 'Additional Options',
    includeSnacks: 'Include Snacks',
    includeDrinks: 'Include Drinks',
    includeSupplements: 'Include Supplements',
    dietaryRestrictions: 'Dietary Restrictions',
    allergiesAndRestrictions: 'Allergies & Restrictions',
    preferredCuisines: 'Preferred Cuisines',
    menuGeneration: 'Meal Plan Generation',
    generateMenuAI: 'Generate Meal Plan with AI',
    generateMenuDescription: 'Click the button below to generate a personalized meal plan based on your preferences.',
    selected: 'Selected',
    dailyTotals: 'Daily Totals',
    manualMenuCreation: 'Manual Meal Plan Creation',
    nutritionTargets: 'Nutrition Targets',
    proteinTarget: 'Protein Target',
    carbsTarget: 'Carbohydrates Target',
    fatTarget: 'Fat Target',
    fiberTarget: 'Fiber Target',
    reviewAndSave: 'Review & Save',
    previewMenu: 'Preview Meal Plan',
    saveMenuDraft: 'Save as Draft',
    publishMenu: 'Publish Meal Plan',
    backToMenus: 'Back to Meal Plans',
    fromDatabase: "from database",
    targetVsGenerated: "Target vs Generated Meal Plan Comparison",
    target: "Target",
    generated: "Generated",
    difference: "Difference",
    menuAccuracy: "Meal Plan Accuracy",
    accurate: "Accurate",
    within5Percent: "within ±5%",
    noTargetDataFound: "No target data found for this client.",
    addingProductCodes: "Adding product codes to ingredients...",
    personalizedRecommendations: "Personalized recommendations",
    generalComments: "General Comments",
    confirmClearMenu: "Are you sure you want to clear the current meal plan and start fresh? This action cannot be undone.",
    startFresh: "Start Fresh",
    previousMenuFound: "Previous Meal Plan Found",
    previousMenuDescription: "We found a previously generated meal plan for",
    fromTime: "from",
    continueOrStartFresh: "Would you like to continue working on it or start fresh?",
    continuePreviousMenu: "Continue Previous Meal Plan",
    loadingClientTargets: "Loading client targets...",
    mainOption: "Main Option",
    alternative: "Alternative",
    otherAlternatives: "Other Alternatives",
    addAlternative: "Add Alternative",
    downloadAsPdf: "Download as PDF",
    upcCache: "UPC Cache",
    ingredientsStored: "ingredients stored",
    upcCacheCleared: "UPC cache cleared successfully!",
    clearCache: "Clear Cache",
    menuAutoSaved: "Meal plan auto-saved locally",
    saveSchemaAndMenu: "Save Schema & Meal Plan",
    showShoppingList: "Show Shopping List",
    hideShoppingList: "Hide Shopping List",

    // Menu Load page specific translations
    editMenu: 'Edit Meal Plan',
    loadedMenu: 'Loaded Meal Plan',
    searchMenus: 'Search by name or client code...',
    filterByClient: 'Filter by client',
    allClients: 'All Clients',
    checkExpiredMenus: 'Check Expired Meal Plans',
    checking: 'Checking...',
    untitledMenu: 'Untitled Meal Plan',
    notAvailable: 'N/A',
    created: 'Created',
    updated: 'Updated',
    activeFrom: 'Active From',
    activeUntil: 'Active Until',
    loadAndEditMenu: 'Load & Edit Meal Plan',
    manageStatus: 'Manage Status',
    noMenusFound: 'No meal plans found',
    noMenusMatchCriteria: 'No meal plans match your search criteria',
    manageMenuStatus: 'Manage Meal Plan Status',
    status: 'Status',
    optional: 'Optional',
    updating: 'Updating...',
    updateStatus: 'Update Status',
    deleteIngredient: 'Delete ingredient',
    mainOption: 'Main Option',
    alternativeOption: 'Alternative Option',
    otherAlternatives: 'Other Alternatives',
    generating: 'Generating...',
    addAlternative: 'Add Alternative',
    makeMain: 'Make Main',
    saving: 'Saving...',
    saveChanges: 'Save Changes',

    // Menu Load page
    loadExistingMenu: 'Load Existing Meal Plan',
    browseMenuLibrary: 'Browse Meal Plan Library',
    loadMenu: 'Load Meal Plan',
    duplicateAndEdit: 'Duplicate & Edit',
    menuPreview: 'Meal Plan Preview',
    menuCreatedBy: 'Created by',
    menuCreatedDate: 'Created',
    menuLastModified: 'Last Modified',
    menuUsageCount: 'Used',
    menuRating: 'Rating',
    noMenusAvailable: 'No meal plans available',
    menuCode: 'Meal Plan Code',
    createYourFirstMenu: 'Create your first meal plan',
    loadSelectedMenu: 'Load Selected Meal Plan',
    menuLoadSuccess: 'Meal plan loaded successfully',
    menuLoadError: 'Failed to load meal plan',

    // User Management page
    userManagementTitle: 'ניהול משתמשים',
    allUsers: 'כל המשתמשים',
    activeUsers: 'משתמשים פעילים',
    inactiveUsers: 'משתמשים לא פעילים',
    newUsers: 'משתמשים חדשים',
    addNewUser: 'הוסף משתמש חדש',
    userProfile: 'פרופיל משתמש',
    userDetails: 'פרטי משתמש',
    personalInformation: 'מידע אישי',
    contactInformation: 'מידע ליצירת קשר',
    healthInformation: 'מידע בריאותי',
    firstName: 'שם פרטי',
    lastName: 'שם משפחה',
    fullName: 'שם מלא',
    dateOfBirth: 'תאריך לידה',
    emailAddress: 'כתובת אימייל',
    phoneNumberField: 'מספר טלפון',
    address: 'כתובת',
    city: 'עיר',
    state: 'מדינה',
    zipCode: 'מיקוד',
    country: 'ארץ',
    emergencyContactName: 'שם איש קשר חירום',
    emergencyContactPhone: 'טלפון איש קשר חירום',
    relationship: 'קשר',
    currentWeight: 'משקל נוכחי',
    goalWeight: 'משקל יעד',
    heightField: 'גובה',
    bodyFatPercentage: 'אחוז שומן גוף',
    medicalHistory: 'היסטוריה רפואית',
    currentMedications: 'תרופות נוכחיות',
    dietaryAllergies: 'אלרגיות תזונתיות',
    foodIntolerances: 'אי סבילות למזון',
    dietaryPreferences: 'העדפות תזונתיות',
    fitnessLevel: 'רמת כושר',
    exerciseFrequency: 'תדירות פעילות גופנית',
    dailyActivityLevel: 'רמת פעילות יומית',
    healthGoals: 'יעדי בריאות',
    nutritionGoals: 'יעדי תזונה',
    userStatus: 'סטטוס משתמש',
    activeStatus: 'פעיל',
    inactiveStatus: 'לא פעיל',
    pendingStatus: 'ממתין',
    suspendedStatus: 'מושעה',
    registrationDate: 'תאריך הרשמה',
    lastLoginDate: 'התחברות אחרונה',
    totalSessions: 'סה"כ סשנים',
    userActions: 'פעולות משתמש',
    viewProfile: 'צפה בפרופיל',
    editProfile: 'ערוך פרופיל',
    deleteUser: 'מחק משתמש',
    suspendUser: 'השעה משתמש',
    activateUser: 'הפעל משתמש',
    resetPassword: 'אפס סיסמה',
    sendMessage: 'שלח הודעה',
    exportUserData: 'ייצא נתוני משתמש',
    userSearchPlaceholder: 'חפש לפי שם, אימייל או מזהה...',
    filterByStatus: 'סנן לפי סטטוס',
    filterByDate: 'סנן לפי תאריך',
    sortByName: 'מיון לפי שם',
    sortByDate: 'מיון לפי תאריך',
    sortByActivity: 'מיון לפי פעילות',
    
    // Nutrition Plan
    searchIngredient: 'חפש מרכיב...',
    editPlan: 'ערוך תוכנית',
    personalizedNutritionPlan: 'תוכנית תזונה מותאמת אישית',
    addMeal: 'הוסף ארוחה',
    addItem: 'הוסף פריט',
    addIngredient: 'הוסף מרכיב',
    mealName: 'שם ארוחה',
    itemName: 'שם פריט',
    portion: 'מנה',
    protein: 'חלבון',
    fat: 'שומן',
    energy: 'אנרגיה',
    calories: 'קלוריות',
    nutritionValues: 'ערכים תזונתיים',
    ingredients: 'מרכיבים',
    alternatives: 'חלופות',
    overview: 'סקירה כללית',
    meals: 'ארוחות',
    nutrition: 'תזונה',
    recommendations: 'המלצות',
    clientInfo: 'מידע לקוח',
    name: 'שם',
    age: 'גיל',
    height: 'גובה',
    weight: 'משקל',
    dailyNutrition: 'תזונה יומית',
    carbs: 'פחמימות',
    supplements: 'תוספי תזונה',
    hydration: 'הידרציה',
    sleep: 'שינה',
    general: 'כללי',
    
    // Settings & Configuration
    accountSettings: 'Account Settings',
    profileSettings: 'Profile Settings',
    notificationSettings: 'Notification Settings',
    privacySettings: 'Privacy Settings',
    appearanceSettings: 'Appearance Settings',
    languageSettings: 'Language Settings',
    themeSettings: 'Theme Settings',
    emailNotifications: 'Email Notifications',
    pushNotifications: 'Push Notifications',
    dataRetention: 'Data Retention',
    twoFactorAuth: 'Two-Factor Authentication',
    passwordChange: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',

    // Forms & Validation
    required: 'Required',
    optional: 'Optional',
    pleaseEnter: 'Please enter',
    pleaseSelect: 'Please select',
    invalidEmail: 'Invalid email address',
    passwordTooShort: 'Password too short',
    passwordsDoNotMatch: 'Passwords do not match',
    fieldRequired: 'This field is required',
    invalidFormat: 'Invalid format',
    valueTooLow: 'Value too low',
    valueTooHigh: 'Value too high',
    invalidPhoneNumber: 'Invalid phone number',
    invalidDate: 'Invalid date',
    futureDate: 'Date cannot be in the future',
    pastDate: 'Date cannot be in the past',

    // Status Messages
    success: 'Success',
    error: 'Error',
    warning: 'Warning',
    info: 'Information',
    saved: 'Saved',
    updated: 'Updated',
    deleted: 'Deleted',
    created: 'Created',
    imported: 'Imported',
    exported: 'Exported',
    synchronized: 'Synchronized',
    published: 'Published',
    unpublished: 'Unpublished',
    activated: 'Activated',
    deactivated: 'Deactivated',
    processing: 'Processing',
    completed: 'Completed',
    failed: 'Failed',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    inProgress: 'In Progress',
    cancelled: 'Cancelled',

    // Data Display
    noDataAvailable: 'No data available',
    noResultsFound: 'No results found',
    emptyList: 'Empty list',
    showMore: 'Show More',
    showLess: 'Show Less',
    viewAll: 'View All',
    viewDetails: 'View Details',
    sortBy: 'Sort by',
    filterBy: 'Filter by',
    groupBy: 'Group by',
    ascending: 'Ascending',
    descending: 'Descending',
    firstPage: 'First Page',
    lastPage: 'Last Page',
    itemsPerPage: 'Items per Page',
    showingItems: 'Showing',
    of: 'of',
    total: 'Total',
    selected: 'Selected',
    all: 'All',
    none: 'None',

    // Chat & Communication
    typeMessage: 'Type a message...',
    sendMessage: 'Send Message',
    chatHistory: 'Chat History',
    conversationStarted: 'Conversation Started',
    messageDelivered: 'Message Delivered',
    messageRead: 'Message Read',
    onlineStatus: 'Online',
    offlineStatus: 'Offline',
    lastSeen: 'Last seen',
    typing: 'Typing...',
    attachFile: 'Attach File',
    sendImage: 'Send Image',
    voiceMessage: 'Voice Message',
    videoCall: 'Video Call',
    loadingMore: 'Loading more messages...',
    loadMore: 'Load more messages',

    // Profile & Professional Info
    specialization: 'Specialization',
    certification: 'Certification',
    yearsOfExperience: 'Years of Experience',
    clinicName: 'Clinic Name',
    clinicAddress: 'Clinic Address',
    profileBio: 'Profile Bio',
    languages: 'Languages',
    consultationFee: 'Consultation Fee',
    availableTimes: 'Available Times',
    professionalTitle: 'Professional Title',
    licenseNumber: 'License Number',
    educationBackground: 'Education Background',
    workExperience: 'Work Experience',
    achievements: 'Achievements',
    publications: 'Publications',
  },
  he: {
    // Navigation & Main Pages
    home: 'לוח בקרה',
    dashboard: 'לוח בקרה',
    about: 'אודות',
    services: 'שירותים',
    contact: 'צור קשר',
    chat: 'צ\'אט',
    allChats: 'כל הצ\'אטים',
    dataGenerator: 'יצירת נתונים',
    nutritionPlan: 'תוכנית תזונה',
    menuCreate: 'יצירת תוכנית ארוחות',
    menuEdit: 'עריכת תוכנית ארוחות',
    menuView: 'צפייה בתוכנית ארוחות',
    menuLoad: 'טעינת תוכנית ארוחות',
    menuAnalysis: 'ניתוח תוכנית ארוחות',
    menus: 'תוכניות ארוחות',
    apiMenus: 'תוכניות ארוחות API',
    clients: 'לקוחות',
    clientProfile: 'פרופיל לקוח',
    clientMenu: 'תוכנית ארוחות לקוח',
    apiClientMenu: 'תוכנית ארוחות לקוח API',
    editClient: 'עריכת לקוח',
    users: 'משתמשים',
    recipes: 'מתכונים',
    recipesPage: 'מתכונים',
    weightLogs: 'יומן משקל',
    menuload: 'טעינת תוכנית ארוחות',
    settings: 'הגדרות',
    register: 'הרשמה',
    login: 'התחברות',
    
    // Common buttons and labels
    submit: 'שלח',
    cancel: 'ביטול',
    save: 'שמור',
    delete: 'מחק',
    signOut: 'התנתק',
    retry: 'נסה שוב',
    edit: 'ערוך',
    loading: 'טוען...',
    search: 'חפש',
    close: 'סגור',
    open: 'פתח',
    next: 'הבא',
    previous: 'הקודם',
    send: 'שלח',
    upload: 'העלה',
    download: 'הורד',
    settings: 'הגדרות',
    profile: 'פרופיל',
    back: 'חזור',
    continue: 'המשך',
    confirm: 'אשר',
    yes: 'כן',
    no: 'לא',
    
    // Client selection
    selectClient: 'בחר לקוח',
    
    // Language switch
    switchLanguage: 'English',
    
    // Error messages
    connectionError: 'שגיאת התחברות',
    failedToLoad: 'טעינת נתוני המשתמש נכשלה. אנא רענן את הדף.',
    
    // Chat page
    selectClientToChat: 'בחר לקוח לשיחה',
    chooseClientFromList: 'בחר לקוח מהרשימה שלך כדי להתחיל לצ\'אט',
    selectAClient: 'בחר לקוח...',
    chatWith: 'צ\'אט עם',
    clientCode: 'קוד לקוח',
    dailyCalories: 'קלוריות יומיות',
    notSet: 'לא נקבע',
    startConversation: 'התחל שיחה',
    chatAboutNutrition: 'על תוכנית התזונה שלהם. תוכל גם לשתף תמונות אוכל לניתוח.',
    noClientSelected: 'לא נבחר לקוח',
    selectClientToStart: 'אנא בחר לקוח מהתפריט הנפתח למעלה כדי להתחיל לצ\'אט על תוכנית התזונה שלהם.',
    messageClient: 'הודעה ל',
    imageSelected: 'תמונה נבחרה',
    uploadedFood: 'אוכל שהועלה',
    failedToUpload: 'העלאת התמונה נכשלה. אנא נסה שוב.',
    failedToSend: 'שליחת ההודעה נכשלה. אנא נסה שוב.',
    failedToLoadClients: 'טעינת הלקוחות נכשלה. אנא נסה שוב מאוחר יותר.',
    failedToLoadClientData: 'טעינת נתוני הלקוח נכשלה. אנא נסה שוב מאוחר יותר.',
    
    // Login page
    login: 'התחברות',
    enterCredentials: 'הכנס את פרטי הגישה שלך כדי לגשת לחשבון שלך',
    email: 'אימייל',
    enterEmail: 'הכנס את האימייל שלך',
    password: 'סיסמה',
    enterPassword: 'הכנס את הסיסמה שלך',
    signIn: 'התחבר',
    signingIn: 'מתחבר...',
    dontHaveAccount: 'אין לך חשבון?',
    register: 'הרשמה',
    failedToSignIn: 'ההתחברות נכשלה. אנא בדוק את פרטי הגישה שלך ונסה שוב.',
    
    // Users page
    userManagement: 'ניהול משתמשים',
    manageUserProfiles: 'נהל פרופילי משתמשים ומידע תזונתי',
    searchUsers: 'חפש משתמשים...',
    users: 'משתמשים',
    viewAndManageUsers: 'צפה ונהל את כל המשתמשים הרשומים',
    userCode: 'קוד משתמש',
    details: 'פרטים',
    actions: 'פעולות',
    noData: 'אין נתונים',
    noUsersFound: 'לא נמצאו משתמשים',
    editUserInformation: 'ערוך מידע משתמש',
    editUserDescription: 'עדכן את מידע הלקוח והעדפותיו.',
    addUserDescription: 'הוסף לקוח חדש למרפאה שלך.',
    heightCm: 'גובה (סמ)',
    weightKg: 'משקל (ק״ג)',
    gender: 'מין',
    activity: 'פעילות',
    goal: 'מטרה',
    selectGender: 'בחר מין',
    male: 'זכר',
    female: 'נקבה',
    selectActivityLevel: 'בחר רמת פעילות',
    sedentary: 'יושב (אין או מעט מאוד פעילות גופנית)',
    lightActivity: 'פעילות קלה (פעילות גופנית קלה/ספורט 1-3 ימים בשבוע)',
    moderateActivity: 'פעילות בינונית (פעילות גופנית בינונית/ספורט 3-5 ימים בשבוע)',
    veryActive: 'פעיל מאוד (פעילות גופנית קשה/ספורט 6-7 ימים בשבוע)',
    extraActive: 'פעיל במיוחד (פעילות גופנית קשה מאוד/ספורט ועבודה פיזית)',
    selectGoal: 'בחר מטרה',
    loseWeight: 'הורדת משקל',
    maintainWeight: 'שמירת משקל',
    gainWeight: 'עלייה במשקל',
    saveChanges: 'שמור שינויים',
    clientManagement: 'ניהול לקוחות',
    manageClientProfiles: 'נהל את פרופילי הלקוחות שלך ומידע',
    addNewClient: 'הוסף לקוח חדש',
    searchClients: 'חפש לקוחות על פי שם, אימייל, קוד או טלפון...',
    clients: 'לקוחות',
    viewAndManageClients: 'צפה ונהל את פרופילי הלקוחות שלך',
    showAll: 'הצג הכל',
    showLess: 'הצג פחות',
    of: 'מתוך',
    noClientsFound: 'לא נמצאו לקוחות שעונים על חיפוש שלך',
    noClientsFoundGeneral: 'לא נמצאו לקוחות. הוסף את הלקוח הראשון שלך כדי להתחיל.',
    contact: 'צור קשר',
    physical: 'גופני',
    goals: 'מטרות',
    macros: 'מאקרו',
    name: 'שם',
    yearsOld: 'שנים',
    city: 'עיר',
    noDataAvailable: 'אין נתונים',
    invalidBmiData: 'נתוני BMI שגויים',
    activityLevel: 'רמת פעילות',
    activity: 'פעילות',
    kcalPerDay: 'קק״ל/יום',
    noMacrosSet: 'מאקרו לא נקבע',
    basicInformation: 'מידע בסיסי',
    clientCode: 'קוד לקוח',
    fullName: 'שם מלא',
    email: 'אימייל',
    phoneNumber: 'מספר טלפון',
    dateOfBirth: 'תאריך לידה',
    physicalInformation: 'מידע גופני',
    age: 'גיל',
    weight: 'משקל',
    height: 'גובה',
    other: 'אחר',
    toning: 'טינינג',
    buildMuscle: 'בניית שריר',
    improveHealth: 'שיפור בריאות',
    nutritionInformation: 'מידע תזונתי',
    dailyTotalCalories: 'קלוריות כוללות יומיות',
    autoCalculated: 'מחושב אוטומטית',
    harrisBenedictInfo: 'מבוסס על נוסחת האריס-בנדיקט באמצעות גיל, מין, משקל, גובה, רמת פעילות ומטרה',
    mifflinStJeorInfo: 'מבוסס על נוסחת מיפלין-סנט ג\'ור באמצעות גיל, מין, משקל, גובה, רמת פעילות ומטרה',
    fillRequiredFieldsToCalculate: 'מלא שדות נדרשים לחישוב',
    isRequired: 'נדרש',
    ageCalculatedFromBirthDate: 'גיל מחושב מתאריך לידה',
    enterAgeOrBirthDate: 'הכנס גיל או תאריך לידה',
    numberOfMeals: 'מספר הארוחות',
    region: 'אזור',
    macrosGrams: 'מאקרו (גרמים)',
    protein: 'חלבון',
    calories: 'קלוריות',
    ingredients: 'מרכיבים',
    carbs: 'פחמימות',
    fat: 'שומן',
    grams: 'גרם',
    totalPercentages: 'סה״כ אחוזים',
    totalCaloriesInTargets: 'סה״כ קלוריות ביעדים',
    macrosSumMatches: 'סכום המאקרו תמיד תואם את הקלוריות:',
    caloriesFormula: 'קלוריות = (4 × חלבון) + (4 × פחמימות) + (9 × שומן)',
    dietaryInformation: 'מידע תזונתי',
    foodAllergies: 'אלרגיות במזון',
    foodAllergiesPlaceholder: 'למשל, פרי עץ, חלב, ביצים (סוגרי ברירה עם פסיקים)',
    foodLimitations: 'הגבלות במזון',
    foodLimitationsPlaceholder: 'טקסט פשוט: צמחוני, קושר, נמוך בנתרן',
    foodLimitationsHelp: '✨ הכנס טקסט פשוט כמו "צמחוני, קושר" והוא יתמיר בעצמו ל["צמחוני", "קושר"]',
    clientPreferences: 'העדפות לקוח',
    foodDiary: 'יומן מזון',
    clientPreferencesPlaceholder: 'טקסט פשוט: אוהב פסטה, מטבח ים תיכוני, ארוחות מהירות',
    clientPreferencesHelp: '✨ הכנס טקסט פשוט כמו "אוהב פסטה" והוא יתמיר בעצמו ל["אוהב פסטה"]',
    recommendations: 'המלצות',
    recommendationsPlaceholder: 'טקסט פשוט: שתה יותר מים, קח ויטמין D, תרגיל 30דקות יומיות',
    recommendationsHelp: '✨ הכנס טקסט פשוט והוא יתמיר בעצמו להמלצות מבנוות',
    saving: 'שמירה...',
    updateClient: 'עדכן לקוח',
    addClient: 'הוסף לקוח',
    failedToLoadClients: 'טעינת הלקוחות נכשלה. אנא נסה שוב.',
    failedToSaveClient: 'שמירת הלקוח נכשלה:',
    failedToUpdateClient: 'עדכון הלקוח נכשל:',
    failedToCreateClient: 'יצירת הלקוח נכשל:',
    failedToDeleteClient: 'נכשל מחיקת הלקוח',
    confirmDelete: 'האם אתה בטוח שברצונך למחוק',
    clientDeleted: 'הלקוח נמחק בהצלחה',
    deleteWarning: 'פעולה זו לא ניתנת לביטול.',
    foodLogsFound: 'נמצאו יומני מזון',
    entriesFound: 'רשומות נמצאו',
    preferencesAutoPopulated: 'העדפות מולאו אוטומטית',
    autoPopulated: 'מולא אוטומטית',
    translateToHebrew: 'תרגם לעברית',
    viewDetailedAnalysis: 'צפה בניתוח תזונתי מפורט',
    detailedAnalysis: 'ניתוח תזונתי מפורט',
    comprehensiveAnalysis: 'ניתוח מקיף של הרגלי האכילה של הלקוח עם המלצות לשיפור',
    analysisSummary: 'סיכום הניתוח',
    totalEntries: 'סה״כ רשומות',
    uniqueFoods: 'מזונות ייחודיים',
    mealCategories: 'קטגוריות ארוחות',
    analysisDate: 'תאריך הניתוח',
    topFoodsByMeal: 'מזונות מובילים לפי קטגוריית ארוחה',
    times: 'פעמים',
    aiDietitianPrompt: 'פקודת ניתוח דיאטנית AI',
    nutritionalAnalysis: 'ניתוח תזונתי',
    analysisDescription: 'ניתוח שנוצר על ידי AI של הרגלי האכילה של הלקוח עם המלצות מותאמות אישית לשיפור.',
    copySystemPrompt: 'העתק פקודת מערכת',
    copyAnalysis: 'העתק ניתוח',
    systemPromptCopied: 'פקודת המערכת הועתקה ללוח!',
    analysisCopied: 'הניתוח הועתק ללוח!',
    
    // BMI Status
    underweight: 'תת משקל',
    normal: 'נורמלי',
    overweight: 'תמוסף',
    obese: 'שמנה',
    
    // Goal values
    lose: 'הורדת משקל',
    maintain: 'שמירת משקל',
    gain: 'עלייה במשקל',
    muscle: 'בניית שריר',
    health: 'שיפור בריאות',
    
    // Activity values
    sedentary: 'יושב (אין או מעט מאוד פעילות גופנית)',
    light: 'פעילות קלה (פעילות גופנית קלה/ספורט 1-3 ימים בשבוע)',
    moderate: 'פעילות בינונית (פעילות גופנית בינונית/ספורט 3-5 ימים בשבוע)',
    very: 'פעיל מאוד (פעילות גופנית קשה/ספורט 6-7 ימים בשבוע)',
    extra: 'פעיל במיוחד (פעילות גופנית קשה מאוד/ספורט ועבודה פיזית)',
    
    // Sorting and Filtering
    sortBy: 'מיון לפי',
    filterBy: 'סינון לפי',
    sortByName: 'מיון לפי שם',
    sortByAge: 'מיון לפי גיל',
    sortByWeight: 'מיון לפי משקל',
    sortByHeight: 'מיון לפי גובה',
    sortByGoal: 'מיון לפי מטרה',
    sortByActivity: 'מיון לפי רמת פעילות',
    sortByCalories: 'מיון לפי קלוריות',
    filterByGoal: 'סינון לפי מטרה',
    filterByActivity: 'סינון לפי רמת פעילות',
    filterByAge: 'סינון לפי גיל',
    filterByGender: 'סינון לפי מין',
    allGoals: 'כל המטרות',
    allActivities: 'כל הפעילויות',
    allAges: 'כל הגילאים',
    allGenders: 'כל המינים',
    ascending: 'ממוין בסדר עולה',
    descending: 'ממוין בסדר יורד',
    clearFilters: 'נקה סינונים',
    applyFilters: 'החל סינונים',
    
    // Dashboard page
    welcomeToDashboard: 'ברוכים הבאים ללוח הבקרה שלכם',
    overviewOfPractice: 'סקירה כללית של המרפאה התזונתית שלכם',
    liveData: 'נתונים בזמן אמת',
    totalClients: 'סה״כ לקוחות',
    menusCreated: 'תפריטים שנוצרו',
    chatSessions: 'סשני צ\'אט',
    weeklyActivity: 'פעילות שבועית',
    quickActions: 'פעולות מהירות',
    commonTasks: 'גישה מהירה למשימות הנפוצות שלכם',
    recentActivity: 'פעילות אחרונה',
    latestUpdates: 'עדכונים אחרונים מהמרפאה שלכם',
    createMenu: 'צור תוכנית ארוחות',
    generateNutritionPlan: 'יצירת תוכנית תזונה',
    manageClients: 'ניהול לקוחות',
    viewEditClients: 'צפייה ועריכת פרופילי לקוחות',
    startChat: 'התחל צ\'אט',
    consultWithAI: 'התייעצות עם עוזר בינה מלאכותית',
    recipeManagement: 'ניהול מתכונים',
    browseRecipes: 'עיון וניהול מתכונים',
    nutritionPlans: 'תוכניות תזונה',
    managePlans: 'ניהול תוכניות תזונה ללקוחות',
    menuoverview: 'תצוגה כללית של תוכנית ארוחות',
    consultations: 'התייעצויות',
    startFirstChat: 'התחל את הצ\'אט הראשון שלך',
    physicalStats: 'סטטיסטיקות גופניות',
    nutritionTargets: 'יעדי תזונה',
    dietaryRestrictions: 'הגבלות תזונתיות',
    userPreferences: 'העדפות משתמש',
    weightChange: 'שינוי משקל',
    activeMenus: 'תפריטים פעילים',
    totalMenus: 'סה״כ תפריטים',
    contactInformation: 'מידע ליצירת קשר',
    heightCm: 'גובה (סמ)',
    goal: 'מטרה',
    preferences: 'העדפות',

    // Client Management
    clientInformation: 'מידע לקוח',
    overviewOfClient: 'סקירה כללית של מידע הלקוח שלך',
    activityLevel: 'רמת פעילות',
    notes: 'הערות',
    editInformation: 'ערוך מידע',
    clientSummary: 'סיכום לקוח',
    kcal: 'קק״ל',
    noMenusYet: 'אין תוכניות ארוחות עדיין',
    createFirstMenu: 'צור את תוכנית הארוחות הראשונה שלך עבור הלקוח הזה',
    menusTotal: 'סה״כ',
    viewAllMenus: 'צפה בכל תוכניות הארוחות',
    chatSession: 'סשן צ\'אט',
    messages: 'הודעות',
    noChatHistory: 'אין היסטוריית צ\'אט',
    startConversationWith: 'התחל שיחה עם הלקוח הזה',
    chatSessionsTotal: 'סשן צ\'אט',
    viewAllChats: 'צפה בכל הצ\'אטים',
    noRecentActivity: 'אין פעילות אחרונה',
    nutritionSummary: 'סיכום תזונתי',
    noMenuDataAvailable: 'אין נתוני תוכנית ארוחות זמינים',
    updateInfo: 'עדכן מידע',
    addNewClient: 'הוסף לקוח חדש',
    clientCode: 'קוד לקוח',
    clientName: 'Client Name',
    phoneNumber: 'Phone Number',
    birthDate: 'Birth Date',
    medicalConditions: 'Medical Conditions',
    allergies: 'Allergies',
    preferences: 'Preferences',
    emergencyContact: 'Emergency Contact',

    // Menu Management
    menuName: 'שם תוכנית ארוחות',
    menuDescription: 'תיאור תוכנית ארוחות',
    targetCalories: 'קלוריות יעד',
    mealPlan: 'תוכנית ארוחות',
    breakfast: 'ארוחת בוקר',
    lunch: 'ארוחת צהריים',
    dinner: 'ארוחת ערב',
    snacks: 'חטיפים',
    totalNutrition: 'Total Nutrition',
    macroBreakdown: 'Macro Breakdown',
    micronutrients: 'Micronutrients',
    vitamins: 'Vitamins',
    minerals: 'Minerals',
    fiber: 'Fiber',
    sugar: 'Sugar',
    sodium: 'Sodium',
    potassium: 'Potassium',
    calculateNutrition: 'Calculate Nutrition',
    generateMenu: 'Generate Meal Plan',
    saveMenu: 'Save Meal Plan',
    loadMenu: 'Load Meal Plan',
    duplicateMenu: 'Duplicate Meal Plan',
    deleteMenu: 'Delete Meal Plan',
    printMenu: 'Print Meal Plan',
    shareMenu: 'Share Meal Plan',

    // Ingredient Portion Dialog
    setPortion: 'Set Portion Size',
    portionDialogDescription: 'Enter the amount in grams and a household measurement. The nutrition values will be automatically adjusted based on the 100g serving size from the database.',
    amountInGrams: 'Amount (grams)',
    householdMeasure: 'Household Measure',
    householdMeasurePlaceholder: 'e.g., 1 cup, 2 tbsp, 1 medium apple',
    adjustedNutrition: 'Adjusted Nutrition',
    basedOn100g: 'Based on 100g serving',
    ratio: 'Ratio',
    pleaseFillAllFields: 'Please fill in all fields',
    pleaseEnterValidAmount: 'Please enter a valid amount greater than 0',
    editPortion: 'Edit portion size',
    ingredient: 'Ingredient',
    within5Percent: 'within ±5%',
    within10Percent: 'within ±10%',
    deleteIngredient: 'Delete ingredient',
    makeMain: 'Make Main',
    makeMainTooltip: 'Make this the main option',

    // Analytics & Reporting
    analyticsOverview: 'Analytics Overview',
    clientProgress: 'Client Progress',
    nutritionTrends: 'Nutrition Trends',
    goalAchievement: 'Goal Achievement',
    complianceRate: 'Compliance Rate',
    weeklyReport: 'Weekly Report',
    monthlyReport: 'Monthly Report',
    customReport: 'Custom Report',
    exportReport: 'Export Report',
    generateReport: 'Generate Report',
    reportPeriod: 'Report Period',
    dateRange: 'Date Range',
    fromDate: 'From Date',
    toDate: 'To Date',
    
    // API & Data Management
    apiConfiguration: 'API Configuration',
    dataImport: 'Data Import',
    dataExport: 'Data Export',
    syncData: 'Sync Data',
    backupData: 'Backup Data',
    restoreData: 'Restore Data',
    apiKey: 'API Key',
    apiEndpoint: 'API Endpoint',
    connectionStatus: 'Connection Status',
    connected: 'Connected',
    disconnected: 'Disconnected',
    lastSync: 'Last Sync',
    syncInProgress: 'Sync in Progress',
    
    // Recipes page
    healthyDeliciousRecipes: 'Healthy & Delicious Recipes',
    professionalRecipes: 'Professional nutrition recipes curated by experts for optimal health and taste',
    professionalRecipesDescription: 'Professional nutrition recipes curated by experts for optimal health and taste',
    recipesAvailable: '120+ Recipes',
    recipesCount: '120+ Recipes',
    expertApproved: 'Expert Approved',
    professionalRecipeCount: 'professional recipe',
    professionalRecipe: 'professional recipe',
    pluralSuffix: 's',
    serving: 'serving',
    salads: 'Salads',
    warmDishes: 'Warm Dishes',
    appetizers: 'Appetizers',
    more: 'More',
    howToMakeIt: 'How to make it',
    tip: 'Tip',
    printRecipe: 'Print Recipe',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    healthy: 'Healthy',
    quick: 'Quick',
    vegetarian: 'Vegetarian',
    vegan: 'Vegan',
    glutenFree: 'Gluten Free',
    dairyFree: 'Dairy Free',
    lowCarb: 'Low Carb',
    highProtein: 'High Protein',
    mediterranean: 'Mediterranean',
    fiberRich: 'Fiber Rich',
    comfortFood: 'Comfort Food',
    makeAhead: 'Make Ahead',
    mealPrep: 'Meal Prep',
    translating: 'Translating...',
    translateRecipes: 'Translate Recipes',
    translatingRecipes: 'Translating recipes...',
    recipeDifficulty: 'Difficulty',
    recipeTime: 'Time',
    recipeServings: 'Servings',
    recipeIngredients: 'Ingredients',
    recipeInstructions: 'Instructions',
    recipeTips: 'Tips',
    recipeMacros: 'Nutrition Facts',
    closeRecipe: 'Close Recipe',

    // Weight Logs page
    weightLogsDescription: 'Track and analyze client progress with comprehensive measurement data and beautiful visualizations',
    selectClient: 'Select Client',
    dateRange: 'Date Range',
    searchPlaceholder: 'Search measurements...',
    chartType: 'Chart Type',
    selectMetrics: 'Select Metrics to Display',
    progressChart: 'Progress Chart',
    progressChartDescription: 'Visual representation of client progress over time',
    refresh: 'Refresh',
    export: 'Export',
    loadingData: 'Loading data...',
    measurementHistory: 'Measurement History',
    measurementHistoryDescription: 'Detailed view of all measurements',
    totalMeasurements: 'Total Measurements',
    currentWeight: 'Current Weight',
    bodyFatPercent: 'Body Fat %',
    avgWeight: 'Avg Weight',
    periodAverage: 'Period average',
    noDataAvailableForFilters: 'No data available for the selected filters',
    pleaseSelectClientToView: 'Please select a client to view their weight logs',
    noWeightLogsFound: 'No weight logs found for the selected client',
    tryDifferentClientOrDateRange: 'Try selecting a different client or adjusting the date range',
    last7Days: 'Last 7 days',
    last30Days: 'Last 30 days',
    last90Days: 'Last 90 days',
    lastYear: 'Last year',
    allTime: 'All time',
    lineChart: 'Line Chart',
    areaChart: 'Area Chart',
    barChart: 'Bar Chart',
    weightKg: 'משקל (ק״ג)',
    bodyFatPercentage: 'Body Fat %',
    waistCm: 'Waist (cm)',
    hipCm: 'Hip (cm)',
    armCm: 'Arm (cm)',

    // Menu Create page
    createNewMenu: 'Create New Meal Plan',
    menuCreationWizard: 'Meal Plan Creation Wizard',
    buildNutritionPlan: 'Build a comprehensive nutrition plan for your client',
    menuBasics: 'Meal Plan Basics',
    clientSelection: 'Client Selection',
    selectTargetClient: 'Select the target client for this meal plan',
    noClientSelectedMenu: 'No client selected',
    menuNameLabel: 'Meal Plan Name',
    menuNamePlaceholder: 'Enter a descriptive name for this meal plan',
    menuDescriptionLabel: 'Meal Plan Description',
    menuDescriptionPlaceholder: 'Describe the purpose and goals of this meal plan',
    targetCaloriesLabel: 'Target Daily Calories',
    targetCaloriesPlaceholder: 'Enter target calories (e.g., 2000)',
    menuDuration: 'Meal Plan Duration',
    singleDay: 'Single Day',
    threeDays: '3 Days',
    oneWeek: '1 Week',
    twoWeeks: '2 Weeks',
    oneMonth: '1 Month',
    mealStructure: 'Meal Structure',
    includedMeals: 'Included Meals',
    additionalOptions: 'Additional Options',
    includeSnacks: 'Include Snacks',
    includeDrinks: 'Include Drinks',
    includeSupplements: 'Include Supplements',
    dietaryRestrictions: 'Dietary Restrictions',
    allergiesAndRestrictions: 'Allergies & Restrictions',
    preferredCuisines: 'Preferred Cuisines',
    menuGeneration: 'Meal Plan Generation',
    generateMenuAI: 'Generate Meal Plan with AI',
    generateMenuDescription: 'Click the button below to generate a personalized meal plan based on your preferences.',
    selected: 'Selected',
    dailyTotals: 'Daily Totals',
    manualMenuCreation: 'Manual Meal Plan Creation',
    nutritionTargets: 'Nutrition Targets',
    proteinTarget: 'Protein Target',
    carbsTarget: 'Carbohydrates Target',
    fatTarget: 'Fat Target',
    fiberTarget: 'Fiber Target',
    reviewAndSave: 'Review & Save',
    previewMenu: 'Preview Meal Plan',
    saveMenuDraft: 'Save as Draft',
    publishMenu: 'Publish Meal Plan',
    backToMenus: 'Back to Meal Plans',
    fromDatabase: "from database",
    targetVsGenerated: "Target vs Generated Meal Plan Comparison",
    target: "Target",
    generated: "Generated",
    difference: "Difference",
    menuAccuracy: "Meal Plan Accuracy",
    accurate: "Accurate",
    within5Percent: "within ±5%",
    noTargetDataFound: "No target data found for this client.",
    addingProductCodes: "Adding product codes to ingredients...",
    personalizedRecommendations: "Personalized recommendations",
    generalComments: "General Comments",
    confirmClearMenu: "Are you sure you want to clear the current meal plan and start fresh? This action cannot be undone.",
    startFresh: "Start Fresh",
    previousMenuFound: "Previous Meal Plan Found",
    previousMenuDescription: "We found a previously generated meal plan for",
    fromTime: "from",
    continueOrStartFresh: "Would you like to continue working on it or start fresh?",
    continuePreviousMenu: "Continue Previous Meal Plan",
    loadingClientTargets: "Loading client targets...",
    mainOption: "Main Option",
    alternative: "Alternative",
    otherAlternatives: "Other Alternatives",
    addAlternative: "Add Alternative",
    downloadAsPdf: "Download as PDF",
    upcCache: "UPC Cache",
    ingredientsStored: "ingredients stored",
    upcCacheCleared: "UPC cache cleared successfully!",
    clearCache: "Clear Cache",
    menuAutoSaved: "Meal plan auto-saved locally",
    saveSchemaAndMenu: "Save Schema & Meal Plan",
    showShoppingList: "Show Shopping List",
    hideShoppingList: "Hide Shopping List",

    // Menu Load page specific translations
    editMenu: 'Edit Meal Plan',
    loadedMenu: 'Loaded Meal Plan',
    searchMenus: 'Search by name or client code...',
    filterByClient: 'Filter by client',
    allClients: 'All Clients',
    checkExpiredMenus: 'Check Expired Meal Plans',
    checking: 'Checking...',
    untitledMenu: 'Untitled Meal Plan',
    notAvailable: 'N/A',
    created: 'Created',
    updated: 'Updated',
    activeFrom: 'Active From',
    activeUntil: 'Active Until',
    loadAndEditMenu: 'Load & Edit Meal Plan',
    manageStatus: 'Manage Status',
    noMenusFound: 'No meal plans found',
    noMenusMatchCriteria: 'No meal plans match your search criteria',
    manageMenuStatus: 'Manage Meal Plan Status',
    status: 'Status',
    optional: 'Optional',
    updating: 'Updating...',
    updateStatus: 'Update Status',
    deleteIngredient: 'Delete ingredient',
    mainOption: 'Main Option',
    alternativeOption: 'Alternative Option',
    otherAlternatives: 'Other Alternatives',
    generating: 'Generating...',
    addAlternative: 'Add Alternative',
    makeMain: 'Make Main',
    saving: 'Saving...',
    saveChanges: 'Save Changes',

    // Menu Load page
    loadExistingMenu: 'Load Existing Meal Plan',
    browseMenuLibrary: 'Browse Meal Plan Library',
    loadMenu: 'Load Meal Plan',
    duplicateAndEdit: 'Duplicate & Edit',
    menuPreview: 'Meal Plan Preview',
    menuCreatedBy: 'Created by',
    menuCreatedDate: 'Created',
    menuLastModified: 'Last Modified',
    menuUsageCount: 'Used',
    menuRating: 'Rating',
    noMenusAvailable: 'No meal plans available',
    menuCode: 'Meal Plan Code',
    createYourFirstMenu: 'Create your first meal plan',
    loadSelectedMenu: 'Load Selected Meal Plan',
    menuLoadSuccess: 'Meal plan loaded successfully',
    menuLoadError: 'Failed to load meal plan',

    // User Management page
    userManagementTitle: 'ניהול משתמשים',
    allUsers: 'כל המשתמשים',
    activeUsers: 'משתמשים פעילים',
    inactiveUsers: 'משתמשים לא פעילים',
    newUsers: 'משתמשים חדשים',
    addNewUser: 'הוסף משתמש חדש',
    userProfile: 'פרופיל משתמש',
    userDetails: 'פרטי משתמש',
    personalInformation: 'מידע אישי',
    contactInformation: 'מידע ליצירת קשר',
    healthInformation: 'מידע בריאותי',
    firstName: 'שם פרטי',
    lastName: 'שם משפחה',
    fullName: 'שם מלא',
    dateOfBirth: 'תאריך לידה',
    emailAddress: 'כתובת אימייל',
    phoneNumberField: 'מספר טלפון',
    address: 'כתובת',
    city: 'עיר',
    state: 'מדינה',
    zipCode: 'מיקוד',
    country: 'ארץ',
    emergencyContactName: 'שם איש קשר חירום',
    emergencyContactPhone: 'טלפון איש קשר חירום',
    relationship: 'קשר',
    currentWeight: 'משקל נוכחי',
    goalWeight: 'משקל יעד',
    heightField: 'גובה',
    bodyFatPercentage: 'אחוז שומן גוף',
    medicalHistory: 'היסטוריה רפואית',
    currentMedications: 'תרופות נוכחיות',
    dietaryAllergies: 'אלרגיות תזונתיות',
    foodIntolerances: 'אי סבילות למזון',
    dietaryPreferences: 'העדפות תזונתיות',
    fitnessLevel: 'רמת כושר',
    exerciseFrequency: 'תדירות פעילות גופנית',
    dailyActivityLevel: 'רמת פעילות יומית',
    healthGoals: 'יעדי בריאות',
    nutritionGoals: 'יעדי תזונה',
    userStatus: 'סטטוס משתמש',
    activeStatus: 'פעיל',
    inactiveStatus: 'לא פעיל',
    pendingStatus: 'ממתין',
    suspendedStatus: 'מושעה',
    registrationDate: 'תאריך הרשמה',
    lastLoginDate: 'התחברות אחרונה',
    totalSessions: 'סה"כ סשנים',
    userActions: 'פעולות משתמש',
    viewProfile: 'צפה בפרופיל',
    editProfile: 'ערוך פרופיל',
    deleteUser: 'מחק משתמש',
    suspendUser: 'השעה משתמש',
    activateUser: 'הפעל משתמש',
    resetPassword: 'אפס סיסמה',
    sendMessage: 'שלח הודעה',
    exportUserData: 'ייצא נתוני משתמש',
    userSearchPlaceholder: 'חפש לפי שם, אימייל או מזהה...',
    filterByStatus: 'סנן לפי סטטוס',
    filterByDate: 'סנן לפי תאריך',
    sortByName: 'מיון לפי שם',
    sortByDate: 'מיון לפי תאריך',
    sortByActivity: 'מיון לפי פעילות',
    
    // Nutrition Plan
    searchIngredient: 'חפש מרכיב...',
    editPlan: 'ערוך תוכנית',
    personalizedNutritionPlan: 'תוכנית תזונה מותאמת אישית',
    addMeal: 'הוסף ארוחה',
    addItem: 'הוסף פריט',
    addIngredient: 'הוסף מרכיב',
    mealName: 'שם ארוחה',
    itemName: 'שם פריט',
    portion: 'מנה',
    protein: 'חלבון',
    fat: 'שומן',
    energy: 'אנרגיה',
    calories: 'קלוריות',
    nutritionValues: 'ערכים תזונתיים',
    ingredients: 'מרכיבים',
    alternatives: 'חלופות',
    overview: 'סקירה כללית',
    meals: 'ארוחות',
    nutrition: 'תזונה',
    recommendations: 'המלצות',
    clientInfo: 'מידע לקוח',
    name: 'שם',
    age: 'גיל',
    height: 'גובה',
    weight: 'משקל',
    dailyNutrition: 'תזונה יומית',
    carbs: 'פחמימות',
    supplements: 'תוספי תזונה',
    hydration: 'הידרציה',
    sleep: 'שינה',
    general: 'כללי',
    
    // Settings & Configuration
    accountSettings: 'Account Settings',
    profileSettings: 'Profile Settings',
    notificationSettings: 'Notification Settings',
    privacySettings: 'Privacy Settings',
    appearanceSettings: 'Appearance Settings',
    languageSettings: 'Language Settings',
    themeSettings: 'Theme Settings',
    emailNotifications: 'Email Notifications',
    pushNotifications: 'Push Notifications',
    dataRetention: 'Data Retention',
    twoFactorAuth: 'Two-Factor Authentication',
    passwordChange: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',

    // Forms & Validation
    required: 'Required',
    optional: 'Optional',
    pleaseEnter: 'Please enter',
    pleaseSelect: 'Please select',
    invalidEmail: 'Invalid email address',
    passwordTooShort: 'Password too short',
    passwordsDoNotMatch: 'Passwords do not match',
    fieldRequired: 'This field is required',
    invalidFormat: 'Invalid format',
    valueTooLow: 'Value too low',
    valueTooHigh: 'Value too high',
    invalidPhoneNumber: 'Invalid phone number',
    invalidDate: 'Invalid date',
    futureDate: 'Date cannot be in the future',
    pastDate: 'Date cannot be in the past',

    // Status Messages
    success: 'Success',
    error: 'Error',
    warning: 'Warning',
    info: 'Information',
    saved: 'Saved',
    updated: 'Updated',
    deleted: 'Deleted',
    created: 'Created',
    imported: 'Imported',
    exported: 'Exported',
    synchronized: 'Synchronized',
    published: 'Published',
    unpublished: 'Unpublished',
    activated: 'Activated',
    deactivated: 'Deactivated',
    processing: 'Processing',
    completed: 'Completed',
    failed: 'Failed',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    inProgress: 'In Progress',
    cancelled: 'Cancelled',

    // Data Display
    noDataAvailable: 'No data available',
    noResultsFound: 'No results found',
    emptyList: 'Empty list',
    showMore: 'Show More',
    showLess: 'Show Less',
    viewAll: 'View All',
    viewDetails: 'View Details',
    sortBy: 'Sort by',
    filterBy: 'Filter by',
    groupBy: 'Group by',
    ascending: 'Ascending',
    descending: 'Descending',
    firstPage: 'First Page',
    lastPage: 'Last Page',
    itemsPerPage: 'Items per Page',
    showingItems: 'Showing',
    of: 'of',
    total: 'Total',
    selected: 'Selected',
    all: 'All',
    none: 'None',

    // Chat & Communication
    typeMessage: 'Type a message...',
    sendMessage: 'Send Message',
    chatHistory: 'Chat History',
    conversationStarted: 'Conversation Started',
    messageDelivered: 'Message Delivered',
    messageRead: 'Message Read',
    onlineStatus: 'Online',
    offlineStatus: 'Offline',
    lastSeen: 'Last seen',
    typing: 'Typing...',
    attachFile: 'Attach File',
    sendImage: 'Send Image',
    voiceMessage: 'Voice Message',
    videoCall: 'Video Call',
    loadingMore: 'Loading more messages...',
    loadMore: 'Load more messages',

    // Profile & Professional Info
    specialization: 'Specialization',
    certification: 'Certification',
    yearsOfExperience: 'Years of Experience',
    clinicName: 'Clinic Name',
    clinicAddress: 'Clinic Address',
    profileBio: 'Profile Bio',
    languages: 'Languages',
    consultationFee: 'Consultation Fee',
    availableTimes: 'Available Times',
    professionalTitle: 'Professional Title',
    licenseNumber: 'License Number',
    educationBackground: 'Education Background',
    workExperience: 'Work Experience',
    achievements: 'Achievements',
    publications: 'Publications',
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(languages.en);

  const toggleLanguage = async () => {
    const newLanguage = language === languages.en ? languages.he : languages.en;
    setLanguage(newLanguage);
    // Update document direction based on new language
    document.documentElement.dir = newLanguage === languages.he ? 'rtl' : 'ltr';
    document.documentElement.lang = newLanguage;

    // Notify listeners (e.g., MenuCreate.jsx) to translate menu if needed
    EventBus.emit('translateMenu', newLanguage);
  };

  // Set initial direction and language
  React.useEffect(() => {
    document.documentElement.dir = language === languages.he ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, []);

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, translations: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
} 