import React, { createContext, useState, useContext } from 'react';
import { EventBus } from '@/utils/EventBus';

export const LanguageContext = createContext();

export const languages = {
  en: 'en',
  he: 'he'
};

export const translations = {
  en: {
    // Navigation & Main Pages
    home: 'Dashboard',
    dashboard: 'Dashboard',
    about: 'About',
    services: 'Services',
    contact: 'Contact',
    chat: 'Chat',
    allChats: 'All Chats',
    dataGenerator: 'Data Generator',
    nutritionPlan: 'Nutrition Plan',
    menuCreate: 'Create Menu',
    menuEdit: 'Edit Menu',
    menuView: 'View Menu',
    menuLoad: 'Load Menu',
    menuAnalysis: 'Menu Analysis',
    menus: 'Menus',
    apiMenus: 'API Menus',
    clients: 'Clients',
    clientProfile: 'Client Profile',
    clientMenu: 'Client Menu',
    apiClientMenu: 'API Client Menu',
    editClient: 'Edit Client',
    users: 'Users',
    recipes: 'Recipes',
    recipesPage: 'Recipes',
    weightLogs: 'Weight Logs',
    menuload: 'Menu Load',
    settings: 'Settings',
    register: 'Register',
    login: 'Login',
    
    // Common buttons and labels
    submit: 'Submit',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    signOut: 'Sign Out',
    retry: 'Retry',
    edit: 'Edit',
    loading: 'Loading...',
    search: 'Search',
    close: 'Close',
    open: 'Open',
    next: 'Next',
    previous: 'Previous',
    send: 'Send',
    upload: 'Upload',
    download: 'Download',
    settings: 'Settings',
    profile: 'Profile',
    back: 'Back',
    continue: 'Continue',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    
    // Client selection
    selectClient: 'Select a client',
    
    // Language switch
    switchLanguage: 'עברית',
    
    // Error messages
    connectionError: 'Connection Error',
    failedToLoad: 'Failed to load user data. Please try refreshing the page.',
    
    // Chat page
    selectClientToChat: 'Select Client to Chat With',
    chooseClientFromList: 'Choose a client from your list to start chatting',
    selectAClient: 'Select a client...',
    chatWith: 'Chat with',
    clientCode: 'Client Code',
    dailyCalories: 'Daily calories',
    notSet: 'Not set',
    startConversation: 'Start a Conversation',
    chatAboutNutrition: 'about their nutrition plan. You can also share food images for analysis.',
    noClientSelected: 'No Client Selected',
    selectClientToStart: 'Please select a client from the dropdown above to start chatting about their nutrition plan.',
    messageClient: 'Message',
    imageSelected: 'Image selected',
    uploadedFood: 'Uploaded food',
    failedToUpload: 'Failed to upload image. Please try again.',
    failedToSend: 'Failed to send message. Please try again.',
    failedToLoadClients: 'Failed to load clients. Please try again later.',
    failedToLoadClientData: 'Failed to load client data. Please try again later.',
    
    // Login page
    login: 'Login',
    enterCredentials: 'Enter your credentials to access your account',
    email: 'Email',
    enterEmail: 'Enter your email',
    password: 'Password',
    enterPassword: 'Enter your password',
    signIn: 'Sign In',
    signingIn: 'Signing in...',
    dontHaveAccount: "Don't have an account?",
    register: 'Register',
    failedToSignIn: 'Failed to sign in. Please check your credentials and try again.',
    
    // Users page
    userManagement: 'User Management',
    manageUserProfiles: 'Manage user profiles and dietary information',
    searchUsers: 'Search users...',
    users: 'Users',
    viewAndManageUsers: 'View and manage all registered users',
    userCode: 'User Code',
    details: 'Details',
    actions: 'Actions',
    noData: 'No data',
    noUsersFound: 'No users found',
    editUserInformation: 'Edit User Information',
    editUserDescription: 'Update the client\'s information and preferences.',
    addUserDescription: 'Add a new client to your practice.',
    heightCm: 'Height (cm)',
    weightKg: 'Weight (kg)',
    gender: 'Gender',
    activity: 'Activity',
    goal: 'Goal',
    selectGender: 'Select gender',
    male: 'Male',
    female: 'Female',
    selectActivityLevel: 'Select activity level',
    sedentary: 'Sedentary',
    lightActivity: 'Light Activity',
    moderateActivity: 'Moderate Activity',
    veryActive: 'Very Active',
    extraActive: 'Extra Active',
    selectGoal: 'Select goal',
    loseWeight: 'Lose Weight',
    maintainWeight: 'Maintain Weight',
    gainWeight: 'Gain Weight',
    saveChanges: 'Save Changes',
    clientManagement: 'Client Management',
    manageClientProfiles: 'Manage your client profiles and information',
    addNewClient: 'Add New Client',
    searchClients: 'Search clients by name, email, code, or phone...',
    clients: 'Clients',
    viewAndManageClients: 'View and manage your client profiles',
    showAll: 'Show All',
    showLess: 'Show Less',
    of: 'of',
    noClientsFound: 'No clients found matching your search',
    noClientsFoundGeneral: 'No clients found. Add your first client to get started.',
    contact: 'Contact',
    physical: 'Physical',
    goals: 'Goals',
    macros: 'Macros',
    name: 'Name',
    yearsOld: 'years old',
    city: 'City',
    noDataAvailable: 'No data',
    invalidBmiData: 'Invalid BMI data',
    activityLevel: 'Activity Level',
    activity: 'activity',
    kcalPerDay: 'kcal/day',
    noMacrosSet: 'No macros set',
    basicInformation: 'Basic Information',
    clientCode: 'Client Code',
    fullName: 'Full Name',
    email: 'Email',
    phoneNumber: 'Phone Number',
    dateOfBirth: 'Date of Birth',
    physicalInformation: 'Physical Information',
    age: 'Age',
    weight: 'Weight',
    height: 'Height',
    other: 'Other',
    toning: 'Toning',
    buildMuscle: 'Build Muscle',
    improveHealth: 'Improve Health',
    nutritionInformation: 'Nutrition Information',
    dailyTotalCalories: 'Daily Total Calories',
    autoCalculated: 'Auto-calculated',
    harrisBenedictInfo: 'Based on Harris-Benedict equation using age, gender, weight, height, activity level, and goal',
    mifflinStJeorInfo: 'Based on Mifflin-St Jeor equation using age, gender, weight, height, activity level, and goal',
    fillRequiredFieldsToCalculate: 'Fill required fields to calculate',
    isRequired: 'is required',
    ageCalculatedFromBirthDate: 'Age calculated from birth date',
    enterAgeOrBirthDate: 'Enter age or birth date',
    numberOfMeals: 'Number of Meals',
    region: 'Region',
    macrosGrams: 'Macros (grams)',
    protein: 'Protein',
    ingredients: 'Ingredients',
    carbs: 'Carbohydrates',
    fat: 'Fat',
    grams: 'grams',
    totalPercentages: 'Total Percentages',
    totalCaloriesInTargets: 'Total Calories in Targets',
    macrosSumMatches: 'The sum of macros always matches calories:',
    caloriesFormula: 'calories = (4 × protein) + (4 × carbs) + (9 × fat)',
    dietaryInformation: 'Dietary Information',
    foodAllergies: 'Food Allergies',
    foodAllergiesPlaceholder: 'e.g., nuts, dairy, shellfish (separate with commas)',
    foodLimitations: 'Food Limitations',
    foodLimitationsPlaceholder: 'Simple text: vegetarian, kosher, low sodium (auto-converts to JSON array)',
    foodLimitationsHelp: '✨ Enter simple text like "vegetarian, kosher" and it will auto-convert to ["vegetarian", "kosher"]',
    clientPreferences: 'Client Preferences',
    clientPreferencesPlaceholder: 'Simple text: loves pasta, mediterranean cuisine, quick meals',
    clientPreferencesHelp: '✨ Enter simple text like "loves pasta" and it will auto-convert to ["loves pasta"]',
    recommendations: 'Recommendations',
    recommendationsPlaceholder: 'Simple text: drink more water, take vitamin D, exercise 30min daily',
    recommendationsHelp: '✨ Enter simple text and it will auto-convert to structured recommendations',
    saving: 'Saving...',
    updateClient: 'Update Client',
    addClient: 'Add Client',
    failedToLoadClients: 'Failed to load clients. Please try again.',
    failedToSaveClient: 'Failed to save client:',
    failedToUpdateClient: 'Failed to update client:',
    failedToCreateClient: 'Failed to create client:',
    failedToDeleteClient: 'Failed to delete client',
    confirmDelete: 'Are you sure you want to delete',
    clientDeleted: 'Client deleted successfully',
    deleteWarning: 'This action cannot be undone.',
    
    // BMI Status
    underweight: 'Underweight',
    normal: 'Normal',
    overweight: 'Overweight',
    obese: 'Obese',
    
    // Goal values
    lose: 'Lose Weight',
    maintain: 'Maintain Weight',
    gain: 'Gain Weight',
    muscle: 'Build Muscle',
    health: 'Improve Health',
    
    // Activity values
    sedentary: 'Sedentary',
    light: 'Light Activity',
    moderate: 'Moderate Activity',
    very: 'Very Active',
    extra: 'Extra Active',
    
    // Sorting and Filtering
    sortBy: 'Sort by',
    filterBy: 'Filter by',
    sortByName: 'Sort by Name',
    sortByAge: 'Sort by Age',
    sortByWeight: 'Sort by Weight',
    sortByHeight: 'Sort by Height',
    sortByGoal: 'Sort by Goal',
    sortByActivity: 'Sort by Activity Level',
    sortByCalories: 'Sort by Calories',
    filterByGoal: 'Filter by Goal',
    filterByActivity: 'Filter by Activity Level',
    filterByAge: 'Filter by Age',
    filterByGender: 'Filter by Gender',
    allGoals: 'All Goals',
    allActivities: 'All Activities',
    allAges: 'All Ages',
    allGenders: 'All Genders',
    ascending: 'Ascending',
    descending: 'Descending',
    clearFilters: 'Clear Filters',
    applyFilters: 'Apply Filters',
    
    // Dashboard page
    welcomeToDashboard: 'Welcome to Your Dashboard',
    overviewOfPractice: 'Overview of your nutrition practice',
    liveData: 'Live Data',
    totalClients: 'Total Clients',
    menusCreated: 'Menus Created',
    chatSessions: 'Chat Sessions',
    weeklyActivity: 'Weekly Activity',
    quickActions: 'Quick Actions',
    commonTasks: 'Access your most common tasks quickly',
    recentActivity: 'Recent Activity',
    latestUpdates: 'Latest updates from your practice',
    createMenu: 'Create Menu',
    generateNutritionPlan: 'Generate a nutrition plan',
    manageClients: 'Manage Clients',
    viewEditClients: 'View and edit client profiles',
    startChat: 'Start Chat',
    consultWithAI: 'Consult with AI assistant',
    recipeManagement: 'Recipe Management',
    browseRecipes: 'Browse and manage recipes',
    nutritionPlans: 'Nutrition Plans',
    managePlans: 'Manage client nutrition plans',
    menuoverview: 'Menu Overview',
    consultations: 'Consultations',
    startFirstChat: 'Start Your First Chat',

    // Client Management
    clientInformation: 'Client Information',
    overviewOfClient: 'Overview of your client information',
    activityLevel: 'Activity Level',
    notes: 'Notes',
    editInformation: 'Edit Information',
    clientSummary: 'Client Summary',
    kcal: 'kcal',
    noMenusYet: 'No menus yet',
    createFirstMenu: 'Create your first menu for this client',
    menusTotal: 'total',
    viewAllMenus: 'View All Menus',
    chatSession: 'Chat Session',
    messages: 'messages',
    noChatHistory: 'No chat history',
    startConversationWith: 'Start a conversation with this client',
    chatSessionsTotal: 'chat session',
    viewAllChats: 'View All Chats',
    noRecentActivity: 'No recent activity',
    nutritionSummary: 'Nutrition Summary',
    noMenuDataAvailable: 'No menu data available',
    updateInfo: 'Update Info',
    addNewClient: 'Add New Client',
    clientCode: 'Client Code',
    clientName: 'Client Name',
    phoneNumber: 'Phone Number',
    birthDate: 'Birth Date',
    medicalConditions: 'Medical Conditions',
    allergies: 'Allergies',
    preferences: 'Preferences',
    emergencyContact: 'Emergency Contact',

    // Menu Management
    menuName: 'Menu Name',
    menuDescription: 'Menu Description',
    targetCalories: 'Target Calories',
    mealPlan: 'Meal Plan',
    breakfast: 'Breakfast',
    lunch: 'Lunch',
    dinner: 'Dinner',
    snacks: 'Snacks',
    totalNutrition: 'Total Nutrition',
    macroBreakdown: 'Macro Breakdown',
    micronutrients: 'Micronutrients',
    vitamins: 'Vitamins',
    minerals: 'Minerals',
    fiber: 'Fiber',
    sugar: 'Sugar',
    sodium: 'Sodium',
    potassium: 'Potassium',
    calculateNutrition: 'Calculate Nutrition',
    generateMenu: 'Generate Menu',
    saveMenu: 'Save Menu',
    loadMenu: 'Load Menu',
    duplicateMenu: 'Duplicate Menu',
    deleteMenu: 'Delete Menu',
    printMenu: 'Print Menu',
    shareMenu: 'Share Menu',

    // Analytics & Reporting
    analyticsOverview: 'Analytics Overview',
    clientProgress: 'Client Progress',
    nutritionTrends: 'Nutrition Trends',
    goalAchievement: 'Goal Achievement',
    complianceRate: 'Compliance Rate',
    weeklyReport: 'Weekly Report',
    monthlyReport: 'Monthly Report',
    customReport: 'Custom Report',
    exportReport: 'Export Report',
    generateReport: 'Generate Report',
    reportPeriod: 'Report Period',
    dateRange: 'Date Range',
    fromDate: 'From Date',
    toDate: 'To Date',
    
    // API & Data Management
    apiConfiguration: 'API Configuration',
    dataImport: 'Data Import',
    dataExport: 'Data Export',
    syncData: 'Sync Data',
    backupData: 'Backup Data',
    restoreData: 'Restore Data',
    apiKey: 'API Key',
    apiEndpoint: 'API Endpoint',
    connectionStatus: 'Connection Status',
    connected: 'Connected',
    disconnected: 'Disconnected',
    lastSync: 'Last Sync',
    syncInProgress: 'Sync in Progress',
    
    // Recipes page
    healthyDeliciousRecipes: 'Healthy & Delicious Recipes',
    professionalRecipes: 'Professional nutrition recipes curated by experts for optimal health and taste',
    professionalRecipesDescription: 'Professional nutrition recipes curated by experts for optimal health and taste',
    recipesAvailable: '120+ Recipes',
    recipesCount: '120+ Recipes',
    expertApproved: 'Expert Approved',
    professionalRecipeCount: 'professional recipe',
    professionalRecipe: 'professional recipe',
    pluralSuffix: 's',
    serving: 'serving',
    salads: 'Salads',
    warmDishes: 'Warm Dishes',
    appetizers: 'Appetizers',
    more: 'More',
    howToMakeIt: 'How to make it',
    tip: 'Tip',
    printRecipe: 'Print Recipe',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    healthy: 'Healthy',
    quick: 'Quick',
    vegetarian: 'Vegetarian',
    vegan: 'Vegan',
    glutenFree: 'Gluten Free',
    dairyFree: 'Dairy Free',
    lowCarb: 'Low Carb',
    highProtein: 'High Protein',
    mediterranean: 'Mediterranean',
    fiberRich: 'Fiber Rich',
    comfortFood: 'Comfort Food',
    makeAhead: 'Make Ahead',
    mealPrep: 'Meal Prep',
    translating: 'Translating...',
    translateRecipes: 'Translate Recipes',
    translatingRecipes: 'Translating recipes...',
    recipeDifficulty: 'Difficulty',
    recipeTime: 'Time',
    recipeServings: 'Servings',
    recipeIngredients: 'Ingredients',
    recipeInstructions: 'Instructions',
    recipeTips: 'Tips',
    recipeMacros: 'Nutrition Facts',
    closeRecipe: 'Close Recipe',

    // Weight Logs page
    weightLogsDescription: 'Track and analyze client progress with comprehensive measurement data and beautiful visualizations',
    selectClient: 'Select Client',
    dateRange: 'Date Range',
    searchPlaceholder: 'Search measurements...',
    chartType: 'Chart Type',
    selectMetrics: 'Select Metrics to Display',
    progressChart: 'Progress Chart',
    progressChartDescription: 'Visual representation of client progress over time',
    refresh: 'Refresh',
    export: 'Export',
    loadingData: 'Loading data...',
    measurementHistory: 'Measurement History',
    measurementHistoryDescription: 'Detailed view of all measurements',
    totalMeasurements: 'Total Measurements',
    currentWeight: 'Current Weight',
    bodyFatPercent: 'Body Fat %',
    avgWeight: 'Avg Weight',
    periodAverage: 'Period average',
    noDataAvailableForFilters: 'No data available for the selected filters',
    pleaseSelectClientToView: 'Please select a client to view their weight logs',
    noWeightLogsFound: 'No weight logs found for the selected client',
    tryDifferentClientOrDateRange: 'Try selecting a different client or adjusting the date range',
    last7Days: 'Last 7 days',
    last30Days: 'Last 30 days',
    last90Days: 'Last 90 days',
    lastYear: 'Last year',
    allTime: 'All time',
    lineChart: 'Line Chart',
    areaChart: 'Area Chart',
    barChart: 'Bar Chart',
    weightKg: 'Weight (kg)',
    bodyFatPercentage: 'Body Fat %',
    waistCm: 'Waist (cm)',
    hipCm: 'Hip (cm)',
    armCm: 'Arm (cm)',

    // Menu Create page
    createNewMenu: 'Create New Menu',
    menuCreationWizard: 'Menu Creation Wizard',
    buildNutritionPlan: 'Build a comprehensive nutrition plan for your client',
    menuBasics: 'Menu Basics',
    clientSelection: 'Client Selection',
    selectTargetClient: 'Select the target client for this menu',
    noClientSelectedMenu: 'No client selected',
    menuNameLabel: 'Menu Name',
    menuNamePlaceholder: 'Enter a descriptive name for this menu',
    menuDescriptionLabel: 'Menu Description',
    menuDescriptionPlaceholder: 'Describe the purpose and goals of this menu',
    targetCaloriesLabel: 'Target Daily Calories',
    targetCaloriesPlaceholder: 'Enter target calories (e.g., 2000)',
    menuDuration: 'Menu Duration',
    singleDay: 'Single Day',
    threeDays: '3 Days',
    oneWeek: '1 Week',
    twoWeeks: '2 Weeks',
    oneMonth: '1 Month',
    mealStructure: 'Meal Structure',
    includedMeals: 'Included Meals',
    additionalOptions: 'Additional Options',
    includeSnacks: 'Include Snacks',
    includeDrinks: 'Include Drinks',
    includeSupplements: 'Include Supplements',
    dietaryRestrictions: 'Dietary Restrictions',
    allergiesAndRestrictions: 'Allergies & Restrictions',
    preferredCuisines: 'Preferred Cuisines',
    menuGeneration: 'Menu Generation',
    generateMenuAI: 'Generate Menu with AI',
    generateMenuDescription: 'Click the button below to generate a personalized menu plan based on your preferences.',
    selected: 'Selected',
    dailyTotals: 'Daily Totals',
    manualMenuCreation: 'Manual Menu Creation',
    nutritionTargets: 'Nutrition Targets',
    proteinTarget: 'Protein Target',
    carbsTarget: 'Carbohydrates Target',
    fatTarget: 'Fat Target',
    fiberTarget: 'Fiber Target',
    reviewAndSave: 'Review & Save',
    previewMenu: 'Preview Menu',
    saveMenuDraft: 'Save as Draft',
    publishMenu: 'Publish Menu',
    backToMenus: 'Back to Menus',
    fromDatabase: "from database",
    targetVsGenerated: "Target vs Generated Menu Comparison",
    target: "Target",
    generated: "Generated",
    difference: "Difference",
    menuAccuracy: "Menu Accuracy",
    accurate: "Accurate",
    within5Percent: "within ±5%",
    noTargetDataFound: "No target data found for this client.",
    addingProductCodes: "Adding product codes to ingredients...",
    personalizedRecommendations: "Personalized recommendations",
    generalComments: "General Comments",
    confirmClearMenu: "Are you sure you want to clear the current menu and start fresh? This action cannot be undone.",
    startFresh: "Start Fresh",
    previousMenuFound: "Previous Menu Found",
    previousMenuDescription: "We found a previously generated menu for",
    fromTime: "from",
    continueOrStartFresh: "Would you like to continue working on it or start fresh?",
    continuePreviousMenu: "Continue Previous Menu",
    loadingClientTargets: "Loading client targets...",
    mainOption: "Main Option",
    alternative: "Alternative",
    otherAlternatives: "Other Alternatives",
    addAlternative: "Add Alternative",
    downloadAsPdf: "Download as PDF",
    upcCache: "UPC Cache",
    ingredientsStored: "ingredients stored",
    upcCacheCleared: "UPC cache cleared successfully!",
    clearCache: "Clear Cache",
    menuAutoSaved: "Menu auto-saved locally",
    saveSchemaAndMenu: "Save Schema & Menu Plan",
    showShoppingList: "Show Shopping List",
    hideShoppingList: "Hide Shopping List",

    // Menu Load page specific translations
    editMenu: 'Edit Menu',
    loadedMenu: 'Loaded Menu',
    searchMenus: 'Search by name or client code...',
    filterByClient: 'Filter by client',
    allClients: 'All Clients',
    checkExpiredMenus: 'Check Expired Menus',
    checking: 'Checking...',
    untitledMenu: 'Untitled Menu',
    notAvailable: 'N/A',
    created: 'Created',
    updated: 'Updated',
    activeFrom: 'Active From',
    activeUntil: 'Active Until',
    loadAndEditMenu: 'Load & Edit Menu',
    manageStatus: 'Manage Status',
    noMenusFound: 'No menus found',
    noMenusMatchCriteria: 'No menus match your search criteria',
    manageMenuStatus: 'Manage Menu Status',
    status: 'Status',
    optional: 'Optional',
    updating: 'Updating...',
    updateStatus: 'Update Status',
    deleteIngredient: 'Delete ingredient',
    mainOption: 'Main Option',
    alternativeOption: 'Alternative Option',
    otherAlternatives: 'Other Alternatives',
    generating: 'Generating...',
    addAlternative: 'Add Alternative',
    makeMain: 'Make Main',
    saving: 'Saving...',
    saveChanges: 'Save Changes',

    // Menu Load page
    loadExistingMenu: 'Load Existing Menu',
    browseMenuLibrary: 'Browse Menu Library',
    loadMenu: 'Load Menu',
    duplicateAndEdit: 'Duplicate & Edit',
    menuPreview: 'Menu Preview',
    menuCreatedBy: 'Created by',
    menuCreatedDate: 'Created',
    menuLastModified: 'Last Modified',
    menuUsageCount: 'Used',
    menuRating: 'Rating',
    noMenusAvailable: 'No menus available',
    menuCode: 'Menu Code',
    createYourFirstMenu: 'Create your first menu',
    loadSelectedMenu: 'Load Selected Menu',
    menuLoadSuccess: 'Menu loaded successfully',
    menuLoadError: 'Failed to load menu',

    // User Management page
    userManagementTitle: 'User Management',
    allUsers: 'All Users',
    activeUsers: 'Active Users',
    inactiveUsers: 'Inactive Users',
    newUsers: 'New Users',
    addNewUser: 'Add New User',
    userProfile: 'User Profile',
    userDetails: 'User Details',
    personalInformation: 'Personal Information',
    contactInformation: 'Contact Information',
    healthInformation: 'Health Information',
    firstName: 'First Name',
    lastName: 'Last Name',
    fullName: 'Full Name',
    dateOfBirth: 'Date of Birth',
    emailAddress: 'Email Address',
    phoneNumberField: 'Phone Number',
    address: 'Address',
    city: 'City',
    state: 'State',
    zipCode: 'Zip Code',
    country: 'Country',
    emergencyContactName: 'Emergency Contact Name',
    emergencyContactPhone: 'Emergency Contact Phone',
    relationship: 'Relationship',
    currentWeight: 'Current Weight',
    goalWeight: 'Goal Weight',
    heightField: 'Height',
    bodyFatPercentage: 'Body Fat Percentage',
    medicalHistory: 'Medical History',
    currentMedications: 'Current Medications',
    dietaryAllergies: 'Dietary Allergies',
    foodIntolerances: 'Food Intolerances',
    dietaryPreferences: 'Dietary Preferences',
    fitnessLevel: 'Fitness Level',
    exerciseFrequency: 'Exercise Frequency',
    dailyActivityLevel: 'Daily Activity Level',
    healthGoals: 'Health Goals',
    nutritionGoals: 'Nutrition Goals',
    userStatus: 'User Status',
    activeStatus: 'Active',
    inactiveStatus: 'Inactive',
    pendingStatus: 'Pending',
    suspendedStatus: 'Suspended',
    registrationDate: 'Registration Date',
    lastLoginDate: 'Last Login',
    totalSessions: 'Total Sessions',
    userActions: 'User Actions',
    viewProfile: 'View Profile',
    editProfile: 'Edit Profile',
    deleteUser: 'Delete User',
    suspendUser: 'Suspend User',
    activateUser: 'Activate User',
    resetPassword: 'Reset Password',
    sendMessage: 'Send Message',
    exportUserData: 'Export User Data',
    userSearchPlaceholder: 'Search by name, email, or ID...',
    filterByStatus: 'Filter by Status',
    filterByDate: 'Filter by Date',
    sortByName: 'Sort by Name',
    sortByDate: 'Sort by Date',
    sortByActivity: 'Sort by Activity',
    
    // Nutrition Plan
    searchIngredient: 'Search ingredient...',
    editPlan: 'Edit Plan',
    personalizedNutritionPlan: 'Personalized Nutrition Plan',
    addMeal: 'Add Meal',
    addItem: 'Add Item',
    addIngredient: 'Add Ingredient',
    mealName: 'Meal Name',
    itemName: 'Item Name',
    portion: 'Portion',
    protein: 'Protein',
    fat: 'Fat',
    energy: 'Energy',
    calories: 'kcal',
    nutritionValues: 'Nutrition Values',
    ingredients: 'Ingredients',
    alternatives: 'Alternatives',
    overview: 'Overview',
    meals: 'Meals',
    nutrition: 'Nutrition',
    recommendations: 'Recommendations',
    clientInfo: 'Client Information',
    name: 'Name',
    age: 'Age',
    height: 'Height',
    weight: 'Weight',
    dailyNutrition: 'Daily Nutrition',
    carbs: 'Carbs',
    supplements: 'Supplements',
    hydration: 'Hydration',
    sleep: 'Sleep',
    general: 'General',
    
    // Settings & Configuration
    accountSettings: 'Account Settings',
    profileSettings: 'Profile Settings',
    notificationSettings: 'Notification Settings',
    privacySettings: 'Privacy Settings',
    appearanceSettings: 'Appearance Settings',
    languageSettings: 'Language Settings',
    themeSettings: 'Theme Settings',
    emailNotifications: 'Email Notifications',
    pushNotifications: 'Push Notifications',
    dataRetention: 'Data Retention',
    twoFactorAuth: 'Two-Factor Authentication',
    passwordChange: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',

    // Forms & Validation
    required: 'Required',
    optional: 'Optional',
    pleaseEnter: 'Please enter',
    pleaseSelect: 'Please select',
    invalidEmail: 'Invalid email address',
    passwordTooShort: 'Password too short',
    passwordsDoNotMatch: 'Passwords do not match',
    fieldRequired: 'This field is required',
    invalidFormat: 'Invalid format',
    valueTooLow: 'Value too low',
    valueTooHigh: 'Value too high',
    invalidPhoneNumber: 'Invalid phone number',
    invalidDate: 'Invalid date',
    futureDate: 'Date cannot be in the future',
    pastDate: 'Date cannot be in the past',

    // Status Messages
    success: 'Success',
    error: 'Error',
    warning: 'Warning',
    info: 'Information',
    saved: 'Saved',
    updated: 'Updated',
    deleted: 'Deleted',
    created: 'Created',
    imported: 'Imported',
    exported: 'Exported',
    synchronized: 'Synchronized',
    published: 'Published',
    unpublished: 'Unpublished',
    activated: 'Activated',
    deactivated: 'Deactivated',
    processing: 'Processing',
    completed: 'Completed',
    failed: 'Failed',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    inProgress: 'In Progress',
    cancelled: 'Cancelled',

    // Data Display
    noDataAvailable: 'No data available',
    noResultsFound: 'No results found',
    emptyList: 'Empty list',
    showMore: 'Show More',
    showLess: 'Show Less',
    viewAll: 'View All',
    viewDetails: 'View Details',
    sortBy: 'Sort by',
    filterBy: 'Filter by',
    groupBy: 'Group by',
    ascending: 'Ascending',
    descending: 'Descending',
    firstPage: 'First Page',
    lastPage: 'Last Page',
    itemsPerPage: 'Items per Page',
    showingItems: 'Showing',
    of: 'of',
    total: 'Total',
    selected: 'Selected',
    all: 'All',
    none: 'None',

    // Chat & Communication
    typeMessage: 'Type a message...',
    sendMessage: 'Send Message',
    chatHistory: 'Chat History',
    conversationStarted: 'Conversation Started',
    messageDelivered: 'Message Delivered',
    messageRead: 'Message Read',
    onlineStatus: 'Online',
    offlineStatus: 'Offline',
    lastSeen: 'Last seen',
    typing: 'Typing...',
    attachFile: 'Attach File',
    sendImage: 'Send Image',
    voiceMessage: 'Voice Message',
    videoCall: 'Video Call',
    loadingMore: 'Loading more messages...',
    loadMore: 'Load more messages',

    // Profile & Professional Info
    specialization: 'Specialization',
    certification: 'Certification',
    yearsOfExperience: 'Years of Experience',
    clinicName: 'Clinic Name',
    clinicAddress: 'Clinic Address',
    profileBio: 'Profile Bio',
    languages: 'Languages',
    consultationFee: 'Consultation Fee',
    availableTimes: 'Available Times',
    professionalTitle: 'Professional Title',
    licenseNumber: 'License Number',
    educationBackground: 'Education Background',
    workExperience: 'Work Experience',
    achievements: 'Achievements',
    publications: 'Publications',
  },
  he: {
    // Navigation & Main Pages
    home: 'לוח בקרה',
    dashboard: 'לוח בקרה',
    about: 'אודות',
    services: 'שירותים',
    contact: 'צור קשר',
    chat: 'צ\'אט',
    allChats: 'כל הצ\'אטים',
    dataGenerator: 'יצירת נתונים',
    nutritionPlan: 'תוכנית תזונה',
    menuCreate: 'יצירת תפריט',
    menuEdit: 'עריכת תפריט',
    menuView: 'צפייה בתפריט',
    menuLoad: 'טעינת תפריט',
    menuAnalysis: 'ניתוח תפריט',
    menus: 'תפריטים',
    apiMenus: 'תפריטי API',
    clients: 'לקוחות',
    clientProfile: 'פרופיל לקוח',
    clientMenu: 'תפריט לקוח',
    apiClientMenu: 'תפריט לקוח API',
    editClient: 'עריכת לקוח',
    users: 'משתמשים',
    recipes: 'מתכונים',
    recipesPage: 'מתכונים',
    weightLogs: 'יומן משקל',
    menuload: 'טעינת תפריט',
    settings: 'הגדרות',
    register: 'הרשמה',
    login: 'התחברות',
    
    // Common buttons and labels
    submit: 'שלח',
    cancel: 'ביטול',
    save: 'שמור',
    delete: 'מחק',
    signOut: 'התנתק',
    retry: 'נסה שוב',
    edit: 'ערוך',
    loading: 'טוען...',
    search: 'חפש',
    close: 'סגור',
    open: 'פתח',
    next: 'הבא',
    previous: 'הקודם',
    send: 'שלח',
    upload: 'העלה',
    download: 'הורד',
    settings: 'הגדרות',
    profile: 'פרופיל',
    back: 'חזור',
    continue: 'המשך',
    confirm: 'אשר',
    yes: 'כן',
    no: 'לא',
    
    // Client selection
    selectClient: 'בחר לקוח',
    
    // Language switch
    switchLanguage: 'English',
    
    // Error messages
    connectionError: 'שגיאת התחברות',
    failedToLoad: 'טעינת נתוני המשתמש נכשלה. אנא רענן את הדף.',
    
    // Chat page
    selectClientToChat: 'בחר לקוח לשיחה',
    chooseClientFromList: 'בחר לקוח מהרשימה שלך כדי להתחיל לצ\'אט',
    selectAClient: 'בחר לקוח...',
    chatWith: 'צ\'אט עם',
    clientCode: 'קוד לקוח',
    dailyCalories: 'קלוריות יומיות',
    notSet: 'לא נקבע',
    startConversation: 'התחל שיחה',
    chatAboutNutrition: 'על תוכנית התזונה שלהם. תוכל גם לשתף תמונות אוכל לניתוח.',
    noClientSelected: 'לא נבחר לקוח',
    selectClientToStart: 'אנא בחר לקוח מהתפריט הנפתח למעלה כדי להתחיל לצ\'אט על תוכנית התזונה שלהם.',
    messageClient: 'הודעה ל',
    imageSelected: 'תמונה נבחרה',
    uploadedFood: 'אוכל שהועלה',
    failedToUpload: 'העלאת התמונה נכשלה. אנא נסה שוב.',
    failedToSend: 'שליחת ההודעה נכשלה. אנא נסה שוב.',
    failedToLoadClients: 'טעינת הלקוחות נכשלה. אנא נסה שוב מאוחר יותר.',
    failedToLoadClientData: 'טעינת נתוני הלקוח נכשלה. אנא נסה שוב מאוחר יותר.',
    
    // Login page
    login: 'התחברות',
    enterCredentials: 'הכנס את פרטי הגישה שלך כדי לגשת לחשבון שלך',
    email: 'אימייל',
    enterEmail: 'הכנס את האימייל שלך',
    password: 'סיסמה',
    enterPassword: 'הכנס את הסיסמה שלך',
    signIn: 'התחבר',
    signingIn: 'מתחבר...',
    dontHaveAccount: 'אין לך חשבון?',
    register: 'הרשמה',
    failedToSignIn: 'ההתחברות נכשלה. אנא בדוק את פרטי הגישה שלך ונסה שוב.',
    
    // Users page
    userManagement: 'ניהול משתמשים',
    manageUserProfiles: 'נהל פרופילי משתמשים ומידע תזונתי',
    searchUsers: 'חפש משתמשים...',
    users: 'משתמשים',
    viewAndManageUsers: 'צפה ונהל את כל המשתמשים הרשומים',
    userCode: 'קוד משתמש',
    details: 'פרטים',
    actions: 'פעולות',
    noData: 'אין נתונים',
    noUsersFound: 'לא נמצאו משתמשים',
    editUserInformation: 'ערוך מידע משתמש',
    editUserDescription: 'עדכן את מידע הלקוח והעדפותיו.',
    addUserDescription: 'הוסף לקוח חדש למרפאה שלך.',
    heightCm: 'גובה (סמ)',
    weightKg: 'משקל (ק״ג)',
    gender: 'מין',
    activity: 'פעילות',
    goal: 'מטרה',
    selectGender: 'בחר מין',
    male: 'זכר',
    female: 'נקבה',
    selectActivityLevel: 'בחר רמת פעילות',
    sedentary: 'יושב',
    lightActivity: 'פעילות קלה',
    moderateActivity: 'פעילות בינונית',
    veryActive: 'פעיל מאוד',
    extraActive: 'פעיל במיוחד',
    selectGoal: 'בחר מטרה',
    loseWeight: 'הורדת משקל',
    maintainWeight: 'שמירת משקל',
    gainWeight: 'עלייה במשקל',
    saveChanges: 'שמור שינויים',
    clientManagement: 'ניהול לקוחות',
    manageClientProfiles: 'נהל את פרופילי הלקוחות שלך ומידע',
    addNewClient: 'הוסף לקוח חדש',
    searchClients: 'חפש לקוחות על פי שם, אימייל, קוד או טלפון...',
    clients: 'לקוחות',
    viewAndManageClients: 'צפה ונהל את פרופילי הלקוחות שלך',
    showAll: 'הצג הכל',
    showLess: 'הצג פחות',
    of: 'מתוך',
    noClientsFound: 'לא נמצאו לקוחות שעונים על חיפוש שלך',
    noClientsFoundGeneral: 'לא נמצאו לקוחות. הוסף את הלקוח הראשון שלך כדי להתחיל.',
    contact: 'צור קשר',
    physical: 'גופני',
    goals: 'מטרות',
    macros: 'מאקרו',
    name: 'שם',
    yearsOld: 'שנים',
    city: 'עיר',
    noDataAvailable: 'אין נתונים',
    invalidBmiData: 'נתוני BMI שגויים',
    activityLevel: 'רמת פעילות',
    activity: 'פעילות',
    kcalPerDay: 'קק״ל/יום',
    noMacrosSet: 'מאקרו לא נקבע',
    basicInformation: 'מידע בסיסי',
    clientCode: 'קוד לקוח',
    fullName: 'שם מלא',
    email: 'אימייל',
    phoneNumber: 'מספר טלפון',
    dateOfBirth: 'תאריך לידה',
    physicalInformation: 'מידע גופני',
    age: 'גיל',
    weight: 'משקל',
    height: 'גובה',
    other: 'אחר',
    toning: 'טינינג',
    buildMuscle: 'בניית שריר',
    improveHealth: 'שיפור בריאות',
    nutritionInformation: 'מידע תזונתי',
    dailyTotalCalories: 'קלוריות כוללות יומיות',
    autoCalculated: 'מחושב אוטומטית',
    harrisBenedictInfo: 'מבוסס על נוסחת האריס-בנדיקט באמצעות גיל, מין, משקל, גובה, רמת פעילות ומטרה',
    mifflinStJeorInfo: 'מבוסס על נוסחת מיפלין-סנט ג\'ור באמצעות גיל, מין, משקל, גובה, רמת פעילות ומטרה',
    fillRequiredFieldsToCalculate: 'מלא שדות נדרשים לחישוב',
    isRequired: 'נדרש',
    ageCalculatedFromBirthDate: 'גיל מחושב מתאריך לידה',
    enterAgeOrBirthDate: 'הכנס גיל או תאריך לידה',
    numberOfMeals: 'מספר הארוחות',
    region: 'אזור',
    macrosGrams: 'מאקרו (גרמים)',
    protein: 'חלבון',
    calories: 'קלוריות',
    ingredients: 'מרכיבים',
    carbs: 'פחמימות',
    fat: 'שומן',
    grams: 'גרם',
    totalPercentages: 'סה״כ אחוזים',
    totalCaloriesInTargets: 'סה״כ קלוריות ביעדים',
    macrosSumMatches: 'סכום המאקרו תמיד תואם את הקלוריות:',
    caloriesFormula: 'קלוריות = (4 × חלבון) + (4 × פחמימות) + (9 × שומן)',
    dietaryInformation: 'מידע תזונתי',
    foodAllergies: 'אלרגיות במזון',
    foodAllergiesPlaceholder: 'למשל, פרי עץ, חלב, ביצים (סוגרי ברירה עם פסיקים)',
    foodLimitations: 'הגבלות במזון',
    foodLimitationsPlaceholder: 'טקסט פשוט: צמחוני, קושר, נמוך בנתרן (מתמיר בעצמו למערך JSON)',
    foodLimitationsHelp: '✨ הכנס טקסט פשוט כמו "צמחוני, קושר" והוא יתמיר בעצמו ל["צמחוני", "קושר"]',
    clientPreferences: 'העדפות לקוח',
    clientPreferencesPlaceholder: 'טקסט פשוט: אוהב פסטה, מטבח ים תיכוני, ארוחות מהירות',
    clientPreferencesHelp: '✨ הכנס טקסט פשוט כמו "אוהב פסטה" והוא יתמיר בעצמו ל["אוהב פסטה"]',
    recommendations: 'המלצות',
    recommendationsPlaceholder: 'טקסט פשוט: שתה יותר מים, קח ויטמין D, תרגיל 30דקות יומיות',
    recommendationsHelp: '✨ הכנס טקסט פשוט והוא יתמיר בעצמו להמלצות מבנוות',
    saving: 'שמירה...',
    updateClient: 'עדכן לקוח',
    addClient: 'הוסף לקוח',
    failedToLoadClients: 'טעינת הלקוחות נכשלה. אנא נסה שוב.',
    failedToSaveClient: 'שמירת הלקוח נכשלה:',
    failedToUpdateClient: 'עדכון הלקוח נכשל:',
    failedToCreateClient: 'יצירת הלקוח נכשל:',
    failedToDeleteClient: 'נכשל מחיקת הלקוח',
    confirmDelete: 'האם אתה בטוח שברצונך למחוק',
    clientDeleted: 'הלקוח נמחק בהצלחה',
    deleteWarning: 'פעולה זו לא ניתנת לביטול.',
    
    // BMI Status
    underweight: 'תת משקל',
    normal: 'נורמלי',
    overweight: 'תמוסף',
    obese: 'שמנה',
    
    // Goal values
    lose: 'הורדת משקל',
    maintain: 'שמירת משקל',
    gain: 'עלייה במשקל',
    muscle: 'בניית שריר',
    health: 'שיפור בריאות',
    
    // Activity values
    sedentary: 'יושב',
    light: 'פעילות קלה',
    moderate: 'פעילות בינונית',
    very: 'פעיל מאוד',
    extra: 'פעיל במיוחד',
    
    // Sorting and Filtering
    sortBy: 'מיון לפי',
    filterBy: 'סינון לפי',
    sortByName: 'מיון לפי שם',
    sortByAge: 'מיון לפי גיל',
    sortByWeight: 'מיון לפי משקל',
    sortByHeight: 'מיון לפי גובה',
    sortByGoal: 'מיון לפי מטרה',
    sortByActivity: 'מיון לפי רמת פעילות',
    sortByCalories: 'מיון לפי קלוריות',
    filterByGoal: 'סינון לפי מטרה',
    filterByActivity: 'סינון לפי רמת פעילות',
    filterByAge: 'סינון לפי גיל',
    filterByGender: 'סינון לפי מין',
    allGoals: 'כל המטרות',
    allActivities: 'כל הפעילויות',
    allAges: 'כל הגילאים',
    allGenders: 'כל המינים',
    ascending: 'ממוין בסדר עולה',
    descending: 'ממוין בסדר יורד',
    clearFilters: 'נקה סינונים',
    applyFilters: 'החל סינונים',
    
    // Dashboard page
    welcomeToDashboard: 'ברוכים הבאים ללוח הבקרה שלכם',
    overviewOfPractice: 'סקירה כללית של המרפאה התזונתית שלכם',
    liveData: 'נתונים בזמן אמת',
    totalClients: 'סה״כ לקוחות',
    menusCreated: 'תפריטים שנוצרו',
    chatSessions: 'סשני צ\'אט',
    weeklyActivity: 'פעילות שבועית',
    quickActions: 'פעולות מהירות',
    commonTasks: 'גישה מהירה למשימות הנפוצות שלכם',
    recentActivity: 'פעילות אחרונה',
    latestUpdates: 'עדכונים אחרונים מהמרפאה שלכם',
    createMenu: 'צור תפריט',
    generateNutritionPlan: 'יצירת תוכנית תזונה',
    manageClients: 'ניהול לקוחות',
    viewEditClients: 'צפייה ועריכת פרופילי לקוחות',
    startChat: 'התחל צ\'אט',
    consultWithAI: 'התייעצות עם עוזר בינה מלאכותית',
    recipeManagement: 'ניהול מתכונים',
    browseRecipes: 'עיון וניהול מתכונים',
    nutritionPlans: 'תוכניות תזונה',
    managePlans: 'ניהול תוכניות תזונה ללקוחות',
    menuoverview: 'תצוגה כללית של תפריט',
    consultations: 'התייעצויות',
    startFirstChat: 'התחל את הצ\'אט הראשון שלך',
    // Client Management
    clientInformation: 'מידע לקוח',
    overviewOfClient: 'סקירה כללית של מידע הלקוח שלך',
    activityLevel: 'רמת פעילות',
    notes: 'הערות',
    editInformation: 'ערוך מידע',
    clientSummary: 'סיכום לקוח',
    kcal: 'קק״ל',
    noMenusYet: 'אין תפריטים עדיין',
    createFirstMenu: 'צור את התפריט הראשון שלך עבור הלקוח הזה',
    menusTotal: 'סה״כ',
    viewAllMenus: 'צפה בכל התפריטים',
    chatSession: 'סשן צ\'אט',
    messages: 'הודעות',
    noChatHistory: 'אין היסטוריית צ\'אט',
    startConversationWith: 'התחל שיחה עם הלקוח הזה',
    chatSessionsTotal: 'סשן צ\'אט',
    viewAllChats: 'צפה בכל הצ\'אטים',
    noRecentActivity: 'אין פעילות אחרונה',
    nutritionSummary: 'סיכום תזונתי',
    noMenuDataAvailable: 'אין נתוני תפריט זמינים',
    updateInfo: 'עדכן מידע',
    addNewClient: 'הוסף לקוח חדש',
    clientCode: 'קוד לקוח',
    clientName: 'שם לקוח',
    phoneNumber: 'מספר טלפון',
    birthDate: 'תאריך לידה',
    medicalConditions: 'מצבים רפואיים',
    allergies: 'אלרגיות',
    preferences: 'העדפות',
    emergencyContact: 'איש קשר חירום',

    // Menu Management
    menuName: 'שם תפריט',
    menuDescription: 'תיאור תפריט',
    targetCalories: 'קלוריות יעד',
    mealPlan: 'תוכנית ארוחות',
    breakfast: 'ארוחת בוקר',
    lunch: 'ארוחת צהריים',
    dinner: 'ארוחת ערב',
    snacks: 'חטיפים',
    totalNutrition: 'תזונה כוללת',
    macroBreakdown: 'פירוט מאקרו',
    micronutrients: 'מיקרו נוטריינטים',
    vitamins: 'ויטמינים',
    minerals: 'מינרלים',
    fiber: 'סיבים תזונתיים',
    sugar: 'סוכר',
    sodium: 'נתרן',
    potassium: 'אשלגן',
    calculateNutrition: 'חישוב תזונה',
    generateMenu: 'יצירת תפריט',
    saveMenu: 'שמירת תפריט',
    loadMenu: 'טעינת תפריט',
    loadAndEditMenu: 'טען וערוך תפריט',
    duplicateMenu: 'שכפול תפריט',
    deleteMenu: 'מחיקת תפריט',
    printMenu: 'הדפסת תפריט',
    shareMenu: 'שיתוף תפריט',

    // Analytics & Reporting
    analyticsOverview: 'סקירת אנליטיקה',
    clientProgress: 'התקדמות לקוחות',
    nutritionTrends: 'מגמות תזונתיות',
    goalAchievement: 'השגת יעדים',
    complianceRate: 'שיעור ציות',
    weeklyReport: 'דוח שבועי',
    monthlyReport: 'דוח חודשי',
    customReport: 'דוח מותאם',
    exportReport: 'יצוא דוח',
    generateReport: 'יצירת דוח',
    reportPeriod: 'תקופת הדוח',
    dateRange: 'טווח תאריכים',
    fromDate: 'מתאריך',
    toDate: 'עד תאריך',
    
    // API & Data Management
    apiConfiguration: 'הגדרת API',
    dataImport: 'יבוא נתונים',
    dataExport: 'יצוא נתונים',
    syncData: 'סנכרון נתונים',
    backupData: 'גיבוי נתונים',
    restoreData: 'שחזור נתונים',
    apiKey: 'מפתח API',
    apiEndpoint: 'נקודת קצה API',
    connectionStatus: 'סטטוס חיבור',
    connected: 'מחובר',
    disconnected: 'מנותק',
    lastSync: 'סנכרון אחרון',
    syncInProgress: 'סנכרון בתהליך',
    
    // Recipes page
    healthyDeliciousRecipes: 'מתכונים בריאים וטעימים',
    professionalRecipes: 'מתכונים תזונתיים מקצועיים שנבחרו על ידי מומחים לבריאות ולטעם מיטבי',
    professionalRecipesDescription: 'מתכונים תזונתיים מקצועיים שנבחרו על ידי מומחים לבריאות ולטעם מיטבי',
    recipesAvailable: '120+ מתכונים',
    recipesCount: '120+ מתכונים',
    expertApproved: 'מאושר על ידי מומחים',
    professionalRecipeCount: 'מתכונים מקצועי',
    professionalRecipe: 'מתכונים מקצועי',
    pluralSuffix: 'ים',
    serving: 'מנה',
    salads: 'סלטים',
    warmDishes: 'מנות חמות',
    appetizers: 'מתאבנים',
    more: 'עוד',
    howToMakeIt: 'איך להכין',
    tip: 'טיפ',
    printRecipe: 'הדפס מתכון',
    easy: 'קל',
    medium: 'בינוני',
    hard: 'קשה',
    healthy: 'בריא',
    quick: 'מהיר',
    vegetarian: 'צמחוני',
    vegan: 'טבעוני',
    glutenFree: 'ללא גלוטן',
    dairyFree: 'ללא חלב',
    lowCarb: 'דל פחמימות',
    highProtein: 'עשיר חלבון',
    mediterranean: 'ים תיכוני',
    fiberRich: 'עשיר סיבים',
    comfortFood: 'אוכל נחמה',
    makeAhead: 'הכנה מראש',
    mealPrep: 'הכנת ארוחות',
    translating: 'מתרגם...',
    translateRecipes: 'תרגם מתכונים',
    translatingRecipes: 'מתרגם מתכונים...',
    recipeDifficulty: 'רמת קושי',
    recipeTime: 'זמן',
    recipeServings: 'מנות',
    recipeIngredients: 'מרכיבים',
    recipeInstructions: 'הוראות הכנה',
    recipeTips: 'טיפים',
    recipeMacros: 'ערכים תזונתיים',
    closeRecipe: 'סגור מתכון',

    // Weight Logs page
    weightLogsDescription: 'עקוב ונתח התקדמות לקוחות עם נתוני מדידה מקיפים וויזואליזציות יפות',
    selectClient: 'בחר לקוח',
    dateRange: 'טווח תאריכים',
    searchPlaceholder: 'חפש מדידות...',
    chartType: 'סוג גרף',
    selectMetrics: 'בחר מדדים להצגה',
    progressChart: 'גרף התקדמות',
    progressChartDescription: 'ייצוג ויזואלי של התקדמות הלקוח לאורך זמן',
    refresh: 'רענן',
    export: 'ייצא',
    loadingData: 'טוען נתונים...',
    measurementHistory: 'היסטוריית מדידות',
    measurementHistoryDescription: 'תצוגה מפורטת של כל המדידות',
    totalMeasurements: 'סה"כ מדידות',
    currentWeight: 'משקל נוכחי',
    bodyFatPercent: 'אחוז שומן גוף %',
    avgWeight: 'משקל ממוצע',
    periodAverage: 'ממוצע תקופה',
    noDataAvailableForFilters: 'אין נתונים זמינים לסינונים שנבחרו',
    pleaseSelectClientToView: 'אנא בחר לקוח כדי לצפות ביומן המשקל שלו',
    noWeightLogsFound: 'לא נמצאו יומני משקל עבור הלקוח שנבחר',
    tryDifferentClientOrDateRange: 'נסה לבחור לקוח אחר או לשנות את טווח התאריכים',
    last7Days: '7 ימים אחרונים',
    last30Days: '30 ימים אחרונים',
    last90Days: '90 ימים אחרונים',
    lastYear: 'שנה אחרונה',
    allTime: 'כל הזמן',
    lineChart: 'גרף קווי',
    areaChart: 'גרף אזור',
    barChart: 'גרף עמודות',
    weightKg: 'משקל (ק"ג)',
    bodyFatPercentage: 'אחוז שומן גוף %',
    waistCm: 'היקף מותניים (ס"מ)',
    hipCm: 'היקף ירכיים (ס"מ)',
    armCm: 'היקף זרוע (ס"מ)',

    // Menu Create page
    createNewMenu: 'צור תפריט חדש',
    menuCreationWizard: 'אשף יצירת תפריט',
    buildNutritionPlan: 'בנה תוכנית תזונה מקיפה עבור הלקוח שלך',
    menuBasics: 'יסודות התפריט',
    clientSelection: 'בחירת לקוח',
    selectTargetClient: 'בחר את הלקוח המיועד עבור התפריט הזה',
    noClientSelectedMenu: 'לא נבחר לקוח',
    menuNameLabel: 'שם התפריט',
    menuNamePlaceholder: 'הכנס שם תיאורי לתפריט הזה',
    menuDescriptionLabel: 'תיאור התפריט',
    menuDescriptionPlaceholder: 'תאר את המטרה והיעדים של התפריט הזה',
    targetCaloriesLabel: 'קלוריות יומיות יעד',
    targetCaloriesPlaceholder: 'הכנס קלוריות יעד (למשל, 2000)',
    menuDuration: 'משך התפריט',
    singleDay: 'יום אחד',
    threeDays: '3 ימים',
    oneWeek: 'שבוע אחד',
    twoWeeks: 'שבועיים',
    oneMonth: 'חודש אחד',
    mealStructure: 'מבנה הארוחות',
    includedMeals: 'ארוחות כלולות',
    additionalOptions: 'אפשרויות נוספות',
    includeSnacks: 'כלול חטיפים',
    includeDrinks: 'כלול משקאות',
    includeSupplements: 'כלול תוספי תזונה',
    dietaryRestrictions: 'הגבלות תזונתיות',
    allergiesAndRestrictions: 'אלרגיות והגבלות',
    preferredCuisines: 'מטבחים מועדפים',
    menuGeneration: 'יצירת תפריט',
    generateMenuAI: 'צור תפריט עם בינה מלאכותית',
    generateMenuDescription: 'לחצו על הכפתור למטה כדי ליצור תוכנית תפריט מותאמת אישית המבוססת על העדפות הלקוחות שלכם.',
    selected: 'נבחר',
    dailyTotals: 'סה"כ יומי',
    manualMenuCreation: 'יצירת תפריט ידנית',
    nutritionTargets: 'יעדי תזונה',
    proteinTarget: 'יעד חלבון',
    carbsTarget: 'יעד פחמימות',
    fatTarget: 'יעד שומן',
    fiberTarget: 'יעד סיבים',
    reviewAndSave: 'סקירה ושמירה',
    previewMenu: 'תצוגה מקדימה של התפריט',
    saveMenuDraft: 'שמור כטיוטה',
    publishMenu: 'פרסם תפריט',
    backToMenus: 'חזור לתפריטים',
    fromDatabase: "מהמסד נתונים",
    targetVsGenerated: "השוואת יעד לתפריט שנוצר",
    target: "יעד",
    generated: "נוצר",
    difference: "הפרש",
    menuAccuracy: "דיוק התפריט",
    accurate: "מדויק",
    within5Percent: "(±5% 1/4)",
    noTargetDataFound: "לא נמצאו נתוני יעד עבור לקוח זה.",
    addingProductCodes: "מוסיף קודי מוצרים למרכיבים...",
    personalizedRecommendations: "המלצות מותאמות אישית",
    generalComments: "הערות כלליות",
    confirmClearMenu: "האם אתה בטוח שברצונך לנקות את התפריט הנוכחי ולהתחיל מחדש? פעולה זו לא ניתנת לביטול.",
    startFresh: "התחל מחדש",
    previousMenuFound: "נמצא תפריט קודם",
    previousMenuDescription: "מצאנו תפריט שנוצר קודם עבור",
    fromTime: "מ",
    continueOrStartFresh: "האם תרצה להמשיך לעבוד עליו או להתחיל מחדש?",
    continuePreviousMenu: "המשך תפריט קודם",
    loadingClientTargets: "טוען יעדי לקוח...",
    mainOption: "אפשרות ראשית",
    alternative: "חלופה",
    otherAlternatives: "חלופות נוספות",
    addAlternative: "הוסף חלופה",
    downloadAsPdf: "הורד כקובץ PDF",
    upcCache: "מטמון UPC",
    ingredientsStored: "מרכיבים מאוחסנים",
    
    // Menu Load page specific translations
    loadMenu: 'טען וערוך תפריט',
    editMenu: 'ערוך תפריט',
    loadedMenu: 'תפריט נטען',
    searchMenus: 'חפש לפי שם או קוד לקוח...',
    filterByClient: 'סנן לפי לקוח',
    allClients: 'כל הלקוחות',
    checkExpiredMenus: 'בדוק תפריטים פגי תוקף',
    checking: 'בודק...',
    untitledMenu: 'תפריט ללא כותרת',
    notAvailable: 'לא זמין',
    created: 'נוצר',
    updated: 'עודכן',
    activeFrom: 'פעיל מ',
    activeUntil: 'פעיל עד',
    loadAndEditMenu: 'טען וערוך תפריט',
    manageStatus: 'נהל סטטוס',
    noMenusFound: 'לא נמצאו תפריטים',
    noMenusMatchCriteria: 'אין תפריטים התואמים לקריטריונים שלך',
    manageMenuStatus: 'נהל סטטוס תפריט',
    status: 'סטטוס',
    optional: 'אופציונלי',
    updating: 'מעדכן...',
    updateStatus: 'עדכן סטטוס',
    deleteIngredient: 'מחק מרכיב',
    mainOption: 'אפשרות ראשית',
    alternativeOption: 'אפשרות חלופית',
    otherAlternatives: 'חלופות נוספות',
    generating: 'יוצר...',
    addAlternative: 'הוסף חלופה',
    makeMain: 'הפוך לראשי',
    saving: 'שומר...',
    saveChanges: 'שמור שינויים',
    upcCacheCleared: "מטמון UPC נוקה בהצלחה!",
    clearCache: "נקה מטמון",
    menuAutoSaved: "התפריט נשמר אוטומטית מקומית",
    saveSchemaAndMenu: "שמור סכמה ותוכנית תפריט",
    showShoppingList: "הצג רשימת קניות",
    hideShoppingList: "הסתר רשימת קניות",
    loadingMore: 'טוען הודעות נוספות...',
    loadMore: 'טען עוד הודעות',
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(languages.en);

  const toggleLanguage = async () => {
    const newLanguage = language === languages.en ? languages.he : languages.en;
    setLanguage(newLanguage);
    // Update document direction based on new language
    document.documentElement.dir = newLanguage === languages.he ? 'rtl' : 'ltr';
    document.documentElement.lang = newLanguage;

    // Notify listeners (e.g., MenuCreate.jsx) to translate menu if needed
    EventBus.emit('translateMenu', newLanguage);
  };

  // Set initial direction and language
  React.useEffect(() => {
    document.documentElement.dir = language === languages.he ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, []);

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, translations: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
} 